#!/bin/bash

# TODO untangle global vars into function args
configureBubbleDNS() {
  echo "Configuring Bubble DNS"
  # FIXME: write posix compatible code
  $(dirname "${BASH_SOURCE[0]}")/new --output "$DOT_ENV" $BUBBLES_FLAGS
  # Reading newly generated domain name by script above
  HUB_DOMAIN_NAME=$(dotenv get "HUB_DOMAIN_NAME")
  HUB_DOMAIN_SECRET=$(dotenv get "HUB_DOMAIN_SECRET")
  if test -z "$HUB_DOMAIN_NAME" -o -z "$HUB_DOMAIN_SECRET"; then
    echo "Error: cannot allocate domain name"
    exit 1
  fi
}

updateBubbleDNS() {
  local domain secret
  domain="$1"
  secret="$2"
  if test -z "$domain"; then
    echo "Error: cannot find configuration 'domain name'"
    exit 1
  fi
  if test -z "$secret"; then
    echo "Error: cannot find configuration 'domain secret'"
    exit 1
  fi
  echo -n "* Sending request to update $domain record: "
  $(dirname "${BASH_SOURCE[0]}")/update --domain-name "$domain" --bubbles-secret-key "$secret"
}
