#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# TODO untangle global vars into function args
configureBubbleDNS() {
  echo "Configuring Bubble DNS"
  # FIXME: write posix compatible code
  new="$(files -e find-in-path bubble-dns/new)"
  # shellcheck disable=SC2086
  $new --output "$DOT_ENV" $BUBBLES_FLAGS
  # Reading newly generated domain name by script above
  HUB_DOMAIN_NAME=$(dotenv -f "$DOT_ENV" get "HUB_DOMAIN_NAME")
  HUB_DOMAIN_SECRET=$(dotenv -f "$DOT_ENV" get "HUB_DOMAIN_SECRET")
  if test -z "$HUB_DOMAIN_NAME" -o -z "$HUB_DOMAIN_SECRET"; then
    echo "Error: cannot allocate domain name"
    exit 1
  fi
}

updateBubbleDNS() {
  domain="$1"
  secret="$2"
  if test -z "$domain"; then
    echo "Error: cannot find configuration 'domain name'"
    exit 1
  fi
  if test -z "$secret"; then
    echo "Error: cannot find configuration 'domain secret'"
    exit 1
  fi
  printf "* Sending request to update %s record: " "$domain"
  update="$(files -e find-in-path bubble-dns/update)"
  $update --domain-name "$domain" --bubbles-secret-key "$secret"
}
