#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# shellcheck disable=SC2046,SC2086

HUB_BASE_DOMAIN="${HUB_BASE_DOMAIN:-"epam.devops.delivery"}"
while [ "$1" != "" ]; do
  case $1 in
    --parent-domain )   shift
                        HUB_BASE_DOMAIN="$1"
                        ;;
    --output )          shift
                        DOT_ENV="$1"
                        ;;
  esac
  shift
done

if test "$VERBOSE" = "true"; then
  set -x
fi

printf "* Using parent domain: "
color h "$HUB_BASE_DOMAIN"
TEMP=$(mktemp /tmp/superhub.XXXXXX) || exit 1
# shellcheck disable=SC2064
trap "rm -f $TEMP" EXIT

printf "* Resolving new domain name... "
HUB_BUBBLE_DNS_URL=${HUB_BUBBLE_DNS_URL:-"https://prod-dns.bubbles.devops.delivery/"}
HTTP_CODE=$( \
  curl -sL -X POST "$HUB_BUBBLE_DNS_URL" \
      -w "%{http_code}" \
      -o "$TEMP" \
      -H 'Content-Type: application/json;charset=UTF-8' \
      -d "{\"baseDomain\": \"$HUB_BASE_DOMAIN\"}" \
)

# checking if http code is 2**
if test "$(echo $HTTP_CODE | cut -c1-1)" != "2"; then
  cat << EOF | color e
Error

Please try again later!

Troubleshooting info:
* Web services returned error code: $HTTP_CODE
EOF
  printf "* Payload: "
  cat $TEMP
  exit 1
fi
HUB_DOMAIN_NAME="$(jq -r '.domain' < "$TEMP")"
color h "$HUB_DOMAIN_NAME"

if test -n "$DOT_ENV"; then
  dotenv="dotenv -f $DOT_ENV"
  $dotenv set "HUB_DOMAIN_NAME" "$HUB_DOMAIN_NAME"
  $dotenv set "HUB_STACK_NAME" "$(echo "$HUB_DOMAIN_NAME" | cut -d. -f1)"
  $dotenv set "HUB_DOMAIN_SECRET" "$(jq -r '.key' < "$TEMP")"
else
  cat << EOF | color w
  This information is not persisted
EOF
fi
