#!/bin/sh

if test -t 1; then
    color_start="\033[35;1m"
    color_end="\033[0m"
fi

which aws >/dev/null 2>&1 || echo ${color_start}'Please install AWS CLI - https://aws.amazon.com/cli/'${color_end}
which kubectl >/dev/null 2>&1 || echo ${color_start}'Please install KUBECTL - https://kubernetes.io/docs/reference/kubectl/overview/'${color_end}
which eksctl >/dev/null 2>&1 || echo ${color_start}'Please install EKSCTL - https://eksctl.io'${color_end}
which jq >/dev/null 2>&1 || echo ${color_start}'Please install JQ - https://stedolan.github.io/jq/'${color_end}
which yq >/dev/null 2>&1 || echo ${color_start}'Please install YQ v3 - https://github.com/mikefarah/yq'${color_end}
which npm >/dev/null 2>&1 || echo ${color_start}'Please optionally install Node.js and NPM for `hub pull` extension - https://nodejs.org'${color_end}

if ! which aws >/dev/null 2>&1 ||
        ! which kubectl >/dev/null 2>&1 ||
        ! which eksctl >/dev/null 2>&1 ||
        ! which yq >/dev/null 2>&1 ||
        ! which jq >/dev/null 2>&1; then
    echo '... then run `hub extensions update` again'
    exit 1
fi

if test "$(jq -V)" \< "jq-1.6"; then
    echo ${color_start}'We recommend to update JQ to v1.6 or up - https://stedolan.github.io/jq/'${color_end}
fi
if test "$(yq -V)" \< "yq version 4.2.1"; then
    echo ${color_start}'We recommend to update YQ to v4.2.1 or up - https://github.com/mikefarah/yq'${color_end}
fi
