#!/bin/sh
# Copyright (c) 2022 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

while test -n "$1"; do
    case "$1" in
        --omit-optional )
            OMIT_OPTIONAL=1
            ;;
        * )
            echo "Usage: check-tools [--omit-optional]"
    esac
    shift
done

color_start="\033[35;1m"
color_end="\033[0m"

which bash >/dev/null 2>&1 || printf "%bPlease install Bash - https://www.gnu.org/software/bash/%b\n" "$color_start" "$color_end"
which curl >/dev/null 2>&1 || printf "%bPlease install cURL - https://curl.se%b\n" "$color_start" "$color_end"
which kubectl >/dev/null 2>&1 || printf "%bPlease install Kubectl - https://kubernetes.io/docs/reference/kubectl/overview/%b\n" "$color_start" "$color_end"
which jq >/dev/null 2>&1 || printf "%bPlease install JQ - https://stedolan.github.io/jq/%b\n" "$color_start" "$color_end"
which yq >/dev/null 2>&1 || printf "%bPlease install YQ v4.16 - https://github.com/mikefarah/yq%b\n" "$color_start" "$color_end"
if test -z "$OMIT_OPTIONAL"; then
    which npm >/dev/null 2>&1 || printf "%bPlease optionally install Node.js and NPM for \"hubctl pull\" extension - https://nodejs.org%b\n" "$color_start" "$color_end"
    which eksctl >/dev/null 2>&1 || printf "%bPlease optionally install EKSCTL for \"hubctl ext eks\" extension - https://eksctl.io%b\n" "$color_start" "$color_end"
fi

if ! which kubectl >/dev/null 2>&1 ||
        ! which yq >/dev/null 2>&1 ||
        ! which jq >/dev/null 2>&1; then
    exit 1
fi

if test "$(jq -V)" \< "jq-1.6"; then
    printf "%bWe recommend to update JQ to v1.6 or up - https://stedolan.github.io/jq/%b\n" "$color_start" "$color_end"
fi
if test "$(yq --version | awk '{ print $NF }')" \< "4.16"; then
    printf "%bWe recommend to update YQ to v4.16.2 or up - https://github.com/mikefarah/yq%b\n" "$color_start" "$color_end"
fi
