#!/bin/sh

while test -n "$1"; do
    case "$1" in
        --omit-optional )
            OMIT_OPTIONAL=1
            ;;
        * )
            echo "Usage: check-tools [--omit-optional]"
            exit 1
    esac
    shift
done

if test -t 1; then
    color_start="\033[35;1m"
    color_end="\033[0m"
fi

which curl >/dev/null 2>&1 || echo ${color_start}'Please install CURL - https://curl.se'${color_end}
which kubectl >/dev/null 2>&1 || echo ${color_start}'Please install KUBECTL - https://kubernetes.io/docs/reference/kubectl/overview/'${color_end}
which jq >/dev/null 2>&1 || echo ${color_start}'Please install JQ - https://stedolan.github.io/jq/'${color_end}
which yq >/dev/null 2>&1 || echo ${color_start}'Please install YQ v4.16 - https://github.com/mikefarah/yq'${color_end}
if test -z "$OMIT_OPTIONAL"; then
    which npm >/dev/null 2>&1 || echo ${color_start}'Please optionally install Node.js and NPM for `hub pull` extension - https://nodejs.org'${color_end}
    which eksctl >/dev/null 2>&1 || echo ${color_start}'Please optionally install EKSCTL for `hub ext eks` extension - https://eksctl.io'${color_end}
fi
#if ! (which aws >/dev/null 2>&1 || which az >/dev/null 2>&1) ||
if ! which kubectl >/dev/null 2>&1 ||
        ! which yq >/dev/null 2>&1 ||
        ! which jq >/dev/null 2>&1; then
    exit 1
fi

if test "$(jq -V)" \< "jq-1.6"; then
    echo ${color_start}'We recommend to update JQ to v1.6 or up - https://stedolan.github.io/jq/'${color_end}
fi
if test "$(yq --version | awk '{ print $NF }')" \< "4.16"; then
    echo ${color_start}'We recommend to update YQ to v4.16.2 or up - https://github.com/mikefarah/yq'${color_end}
fi
