#!/bin/bash -e
# shellcheck disable=SC2086,SC1118

usage() {
  cat << EOF
Creates infrastructure resources in your aws cloud that has been utilized by hub components

Usage: $(basename "$0")

Parameters:
    --aws-region          AWS Region
    --aws-profile         AWS Profile
    --rm-state-bucket     Delete state bucket as well
    -s  --silent          Suppress console outputs in favor of result codes
    --skip-guide          Suppress "What's next messages"
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message

EOF
}

SILENT=false
RM_BUCKET=false

if [[ ! -f .env ]]; then
  cat << EOF

Error: cannot find .env file. Please run:
  
$ hub stack configure --kubecontext -

EOF
  exit 1
fi

source .env

SILENT=${SILENT:-true}

test -n "$@" && while [ "$1" != "" ]; do
  case $1 in
    --aws-region )      shift
                        export AWS_REGION="$1"
                        ;;
    --aws-profile )     shift
                        export AWS_PROFILE="$1"
                        ;;
    --rm-state-bucket ) RM_BUCKET=true
                        ;;
    -S | --silent )     SILENT=true
                        ;;
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    * )                 usage
                        exit 1
  esac
  shift
done

# TODO: replace this with smth better before script will be moved to extension
SUCCESS=true
pwd=$(dirname "$0")

set +e
SILENT || echo "* Deleting Route53 hosted zone for $HUB_DOMAIN_NAME..."
$pwd/aws/route53-zone/undeploy --domain-name "$HUB_DOMAIN_NAME"
if test "$?" != "0"; then 
  echo "Fail"
  SUCCESS=false
fi

if $RM_BUCKET; then
  SILENT || echo "* Deleting S3 bucket for $BUCKET_AME: not yet implemented!"
  SUCCESS=false
else 
  SILENT || echo "* Deleting S3 bucket for $BUCKET_AME: skip due to user setting"
fi

if ! $SUCCESS; then
  SILENT || echo "Failed to remove one or multiple resources"
  exit 2
fi
