#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.

HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH

hubctl="$(which hubctl 2>/dev/null || true)"
if test -z "$hubctl"; then
  # backward compatibility
  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
  hubctl="$(which hub 2>/dev/null || true)"
fi
if test -z "$hubctl"; then
  color error "hubctl not found in PATH. Please install hubctl first."
  exit 1
fi

is_url() {
  echo "$1" | grep -e '[[:alnum:]]*://' >/dev/null 2>&1
}

usage() {
cat << EOF

Create backup for current stack

Usage:
$ hubctl stack backup create

Creates a backup for entire stack

$  hubctl stack backup create -c component1,component2

Creates a backup for two components

Parameters:
    -t --tag              Backup tags
    -c --component        Components to backup
    -V  --verbose         Verbose outputs for debug purpose
    --tty                 Use TTY (terminal) mode for hubctl
    --no-tty              Do not use TTY (terminal) mode for hubctl
    --                    Separator to define "hubctl" low level parameters (see: "hubctl --help")
    -h  --help            Print this message

EOF
}

if test ! -f "$HUB_WORKDIR/.env"; then
  color error "Error: cannot find .env file in $HUB_WORKDIR"
  exit 1
fi
eval "$(dotenv export -f "$HUB_WORKDIR/.env")"

FULL_STACK=true
HUB_OPTS=

while test "$1" != ""; do
    case $1 in
        -t | --tag )        shift
                            HUB_BACKUP_TAG="$1"
                            ;;
        -c | --component )  shift
                            HUB_OPTS="$HUB_OPTS -c $1"
                            FULL_STACK=false
                            ;;
        --tty )             HUB_OPTS="$HUB_OPTS --tty true"
                            ;;
        --no-tty )          HUB_OPTS="$HUB_OPTS --tty false"
                            ;;
        -V | --verbose )    set -x
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        -- )                shift
                            HUB_OPTS="$HUB_OPTS $*"
                            break
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

if test -z "$HUB_DOMAIN_NAME"; then
  echo "Error: HUB_DOMAIN_NAME has not been defined"
  exit 2
fi

cat << EOF
Creating backup:
* Using domain name: $HUB_DOMAIN_NAME
EOF

if test -n "$HUB_KUBECONFIG" -a -f "$HUB_KUBECONFIG"; then
  KUBECONFIG="$HUB_KUBECONFIG"
  export KUBECONFIG
  echo "* Using kubeconfig: $KUBECONFIG"
elif test -n "$KUBECONFIG" -a -f "$KUBECONFIG"; then
  export KUBECONFIG
  echo "* Using kubeconfig: $KUBECONFIG"
fi

if test -z "$HUB_STATE"; then
  HUB_STATE="$HUB_WORKDIR/.hub/$HUB_DOMAIN_NAME.state"
fi

echo "* Using hubctl state:"
hub_state=$(echo "$HUB_STATE" | sed 's/,/ /g')
for i in ${hub_state}; do
  echo "  - $i"
done

if test -z "$HUB_ELABORATE"; then
  HUB_ELABORATE="$HUB_WORKDIR/.hub/$HUB_DOMAIN_NAME.elaborate"
fi
echo "* Using hubctl elaborate:"
for i in $(echo "$HUB_ELABORATE" | sed "s/,/ /g"); do
  echo "  - $i"
  if ! is_url "$i"; then
    HUB_ELABORATE_FILE=$i
  fi
done

if test -n "$HUB_CLOUD_PROVIDER"; then
  echo "* Using cloud: $HUB_CLOUD_PROVIDER"
  HUB_OPTS="--clouds=$HUB_CLOUD_PROVIDER $HUB_OPTS"
fi

script_dir=$(dirname "$0")

if $FULL_STACK || test -n "$HUB_ELABORATE_FILE" -a ! -e "$HUB_ELABORATE_FILE"; then
  "$script_dir"/hub-stack-elaborate
elif test -n "$HUB_ELABORATE_FILE"; then
  if ! "$script_dir"/check-elaborate "$HUB_ELABORATE_FILE" "$HUB_FILES"; then
    echo "Call:"
    echo "    $ hubctl stack elaborate"
    echo "or update elaborate file timestamp:"
    echo "    $ touch $HUB_ELABORATE_FILE"
    echo
    exit 1
  fi
fi

# export HUB_YAML HUB_FILES HUB_STATE HUB_ELABORATE
if test -z "$HUB_BACKUP_DIR"; then
  HUB_BACKUP_DIR="$HUB_WORKDIR/.hub/backups"
fi

hub_backup_dir="$HUB_BACKUP_DIR"
HUB_BACKUP_DIR="$HUB_BACKUP_DIR/$HUB_DOMAIN_NAME/$(date +"%Y%m%d-%H%M%S")"
mkdir -p "$HUB_BACKUP_DIR"
HUB_BACKUP_DIR=$(files abspath "$HUB_BACKUP_DIR")
export HUB_BACKUP_DIR

rm_empty() {
  if test -z "$(ls -A "$1")"; then
    echo "* deleting empty $1"
    rm -rf "$1"
  fi
}

# shellcheck disable=SC2064
trap "rm_empty $HUB_BACKUP_DIR" EXIT

cat << EOF
* Running CLI command:

  $ hubctl backup create $HUB_ELABORATE -s $HUB_STATE -o $HUB_BACKUP_DIR/hub-bundle.yaml.gz $HUB_OPTS

EOF

# shellcheck disable=SC2086
$hubctl backup create "$HUB_ELABORATE" -s "$HUB_STATE" -o "$HUB_BACKUP_DIR/hub-bundle.yaml.gz" $HUB_OPTS

if test -n "$HUB_BACKUP_TAG"; then
  echo "* Tagging backup: $HUB_BACKUP_TAG"
  tag_path="$hub_backup_dir/tags/$HUB_BACKUP_TAG"
  if test -L "$tag_path"; then
    echo "  Unlinking $tag_path"
    unlink "$tag_path"
  fi
  echo "  Reference to backup: $(basename "$HUB_BACKUP_DIR")"
  mkdir -p "$(dirname "$tag_path")"
  ln -s "$HUB_BACKUP_DIR" "$tag_path"
fi
