#!/bin/bash -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"

usage() {
  cat << EOF
Set or change currently active stack

Usage: hubctl stack set STACK

  where STACK is the name of the stack to set as an active

Note: to see list of available stacks run

  $ hubctl stack ls

EOF
}

if test -z "$1"; then
  usage
  exit 1
fi

if test "$1" = "initialized"; then
  dotfile="$HUB_WORKDIR/.hub/env/.env"
else
  dotfile="$HUB_WORKDIR/.hub/env/$1.env"
fi

if test ! -d .hub/env; then
  color error "Error: no stacks available"
  exit 2
fi

echo "Setting $1 as current"
if test ! -f "$dotfile"; then
  color error "Error: cannot find $1 stack"
  cat << EOF

To see list of available stacks run

  $ hubctl stack ls

EOF
  exit 3
fi


if test -L ".env"; then
  echo "* Unlinking .env"
  unlink ".env"
elif test -f ".env"; then
  echo "* Backing up .env as .env.bak"
  mv ".env" ".env.bak"
fi

if test ! -f ".env"; then
  echo "* Setting .env link to $1"
  ln -sf "$dotfile" ".env"
fi
