#!/bin/bash -e
# shellcheck disable=SC2086,SC1118

usage() {
  cat << EOF
Creates infrastructure resources in your aws cloud that has been utilized by hub components

Usage: $(basename "$0")

Parameters:
    --aws-region          AWS Region
    --aws-profile         AWS Profile
    -s  --silent          Suppress console outputs in favor of result codes
    --skip-guide          Suppress "What's next messages"
    -V  --verbose         Verbose outputs for debug purpose
EOF
}

SILENT=${SILENT:-false}
GUIDE=${GUIDE:-true}

test -f ".env" && source .env

while [ "$1" != "" ]; do
  case $1 in
    --aws-region )      shift
                        export AWS_REGION="$1"
                        ;;
    --aws-profile )     shift
                        export AWS_PROFILE="$1"
                        ;;
    -S | --silent )     SILENT=true
                        ;;
    --skip-guide )      GUIDE=false
                        ;;
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    * )                 usage
                        exit 1
  esac
  shift
done

if test ! -f .env; then
  SILENT || echo "Error: configuration file '.env' does not exist"
  GUIDE && cat << EOF

## What's next?

Please run:
  
$ hub configure --current-kubeconfig

EOF
  exit 1
fi

echo "Deploying AWS prerequisites for $HUB_DOMAIN_NAME stack"
pwd=$(dirname "$0")

echo -n "* S3 bucket $HUB_STATE_BUCKET for deployment state... "
$pwd/aws/s3-bucket/deploy \
  --bucket-name "$HUB_STATE_BUCKET" \
  --aws-region "$AWS_REGION" \
  --acl "private"
  
if test "$?" = "0"; then 
  echo "Done"
else
  echo "Failed"
  exit 4
fi
set -e

set +e
echo -n "* Route53 hosted zone for $HUB_DOMAIN_NAME... "
# shellcheck disable=SC2046,SC2068
NS=$($pwd/aws/route53-zone/deploy --domain-name "$HUB_DOMAIN_NAME" --json)
if test "$?" = "0"; then 
  echo "Done"
else
  echo "Failed"
  exit 3
fi

echo -n "* Sending $HUB_DOMAIN_NAME DNS delegation set: "
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
      "https://api.agilestacks.io/dns/$HUB_DOMAIN_NAME" \
      -H 'Content-Type: application/json;charset=UTF-8' \
      -d "{\"key\": \"$HUB_DOMAIN_KEY\",\"nameservers\": $NS}")

if test "$(echo $HTTP_CODE | cut -c1-1)" != "2"; then
  echo "Failed"
  $SILENT || echo "Something went wrong. Please try again later!"
  exit 2
else 
echo "Done"
fi

set +e
$SILENT || echo "Validating cloud setup"
hub ext aws status --skip-guide
hub_aws_rv="$?"
set -e

if test "$hub_aws_rv" = "0"; then
  $SILENT || cat << EOF

All prerequisites has been deployed. Ready to deploy $HUB_DOMAIN_NAME stack.

## What's next?

Please feel free to run:

$ hub ext stack deploy

EOF
elif test "$hub_aws_rv" = "3"; then
  $SILENT || cat << EOF

One or few prerequisites has not been deployed successfully. 

## What's next?

Please login to AWS console to troubleshoot

Then run again:

$ hub ext aws init 

EOF
fi
