#!/bin/bash -e
# shellcheck disable=SC2068

usage() {
  cat << EOF

Usage: $(basename "$0") <sub command>

Parameters:
    init          Apply hub prerequisite resources to your AWS account
    undeploy      Remove hub prerequisite resources from your AWS account
    status        Check the state of AWS account if it is ready to work with hub CLI
    register      Register Product in AWS marketplace
EOF
}

if test -z "$@"; then
  usage
  exit 1
fi

HUB=${HUB:-hub}

while [ "$1" != "" ]; do
  case $1 in
    init )        $HUB aws init $@
                  ;;
    undeploy )    $HUB aws undeploy $@
                  ;;
    status )      $HUB aws status $@
                  ;;
    register )    $HUB aws register $@
                  ;;
    -h | --help ) usage
                  exit
                  ;;
    * )           usage
                  exit 1
  esac
  shift
done
