#!/bin/bash

usage()
{
    echo "Show stack secret"
    echo "usage: $0 [-s domain-name] [-r secret-reference]"
    exit 0
}

if test -z "$1"; then
    usage;
    exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
        -s | --stack )      shift
                            STACK=$1
                            ;;
        -r | --secret-ref ) shift
                            REF=$(echo $1 | tr -d '"')
                            ;;                            
        - )                 REF=$(cat /dev/stdin | xargs | cut -d " " -f1 | tr -d '"')
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

hub api instance secret get $STACK $REF
