#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH

usage() {
cat << EOF

Assemble hub.yaml.elaborate stack deployment manifest from hub.yaml,
params.yaml-s, and hub-components.yaml-s

Usage:
$ hub stack elaborate

Parameters:
    -V  --verbose          Verbose outputs for debug purpose
    -h --help              Show this message

EOF
}

if test ! -f .env; then
  echo "* Error: configuration '.env' has not been found"
  exit 1
fi
eval "$(dotenv export -f "$HUB_WORKDIR/.env" )"

HUB_OPTS=
while [ "$1" != "" ]; do
    case $1 in
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    --hub-files )       shift
                        HUB_FILES="$1"
                        ;;
    -- )                shift
                        HUB_OPTS="$HUB_OPTS $*"
                        break
                        ;;
    * )                 usage
                        exit 1
    esac
    shift
done

echo "Reconciling deployment plan for $HUB_STACK_NAME"
echo "* Using domain name: $HUB_DOMAIN_NAME"

if test -z "$HUB_FILES"; then
  cat << EOF
Error: cannot find hub definition files (HUB_FILES)"

Probably because stack has not been configured for deployment yet!

Example:
  $ hub configure -f hub.yaml

EOF

  exit 2
fi

if test -z "$HUB_STATE"; then
  if test -f ".hub/$HUB_DOMAIN_NAME.state"; then
    HUB_STATE=".hub/$HUB_DOMAIN_NAME.state"
  fi
fi

# if test -n "$HUB_STATE"; then
#   echo "* Using hub state: $HUB_STATE"
#   HUB_OPTS="$HUB_OPTS -s $HUB_STATE"
# fi

if test -z "$HUB_ELABORATE"; then
  HUB_ELABORATE=".hub/$HUB_DOMAIN_NAME.elaborate"
fi

cat << EOF

Proceeding with: elaborate
* Result will be saved saved to: $HUB_ELABORATE
* Running CLI command:

  $ hub elaborate $HUB_FILES -o $HUB_ELABORATE $HUB_OPTS

EOF

verb="elaborate"
work_dir="$(pwd)"
script_dir=$(dirname "$0")


BEFORE=$(yq -N e .extensions.${verb}.before.[] $HUB_FILES | sort | uniq)
for i in $(echo "$BEFORE" | xargs -n1); do
  if test -f "$work_dir/.hub/$i/before-${verb}"; then
    hook="$work_dir/.hub/$i/before-${verb}"
  elif test -f "$script_dir/$i/before-${verb}"; then
    hook="$script_dir/$i/before-${verb}"
  else
    echo "Warning! cannot find before hook: $i"
    continue
  fi
  echo "Running before ${verb} hook: $i"
  $hook
done


# shellcheck disable=SC2086
hub elaborate $HUB_FILES -o "$HUB_ELABORATE" $HUB_OPTS

AFTER=$(yq -N e .extensions.${verb}.after.[] $HUB_FILES | sort | uniq)
for i in $(echo "$AFTER" | xargs -n1); do
  if test -f "$work_dir/.hub/$i/after-${verb}"; then
    hook="$work_dir/.hub/$i/after-${verb}"
  elif test -f "$script_dir/$i/after-${verb}"; then
    hook="$script_dir/$i/after-${verb}"
  else
    echo "Warning! cannot find after hook: $i"
    continue
  fi
  echo "Running after ${verb} hook: $i"
  $hook
done
