#!/bin/bash -e
# shellcheck disable=SC2086

usage()
{
cat << EOF
Print info about stack in JSON format. Stack parameters and outputs are merged by default with the precedence to the outputs. Execute current script with parameter "-o" to see outputs separately
Usage: $(basename "$0") -s STACK_DOMAIN [-o] [-t]
Parameters:
    -s --stack      domain name of the stack
    -o --split      split stack outpus from parameters
    -m --machine    transform parameters as nested objects for easy parsing
    -c --component  display parameters and outputs for the given component
    -y --yaml       yaml output instead of json (requires yq)
    -r --raw        unconverted output from hub
    -q -jq --query  jq style query for the results (Implicitly enables -m)
    -h --help       print current message
    --              separator for JQ style arguments see more here: https://stedolan.github.io/jq
EOF
}

FORMAT="${FORMAT:-json}"
JQ_ARGS="${JQ_ARGS:- -S}"

dotenv="$(dirname "$0")/env/dotenv -f .env"
set +a
eval $($dotenv export)
set -a

if ! test -t 0; then
    HUB_DOMAIN_NAME=$(< /dev/stdin xargs | cut -d " " -f1 | tr -d '"')
fi

JQ_QUERY="."
while [ "$1" != "" ]; do
    case $1 in
        -s | --stack )      shift
                            HUB_DOMAIN_NAME=$1
                            ;;
        -c | --COMPONENT )  shift
                            HUB_COMPONENT=$1
                            SPLIT_OUTPUTS=1
                            ;;
        -o | --split )      SPLIT_OUTPUTS=1
                            ;;
        -m | --machine )    TRANSFORM=1
                            ;;
        -y | --yaml )       FORMAT="yaml"
                            ;;
        -r | --raw )        RAW_OUTPUT=1
                            ;;
        -q | -jq |--query ) shift
                            TRANSFORM=1
                            JQ_QUERY="$1"
                            ;;
        -v | --verbose )    set -x
                            ;;
        - )                 HUB_DOMAIN_NAME=$(< /dev/stdin xargs | cut -d " " -f1)
                            ;;
        -- )                shift
                            JQ_ARGS="$JQ_ARGS $*"
                            break
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

dotenv="$(dirname "$0")/env/dotenv -f .env"
HUB_KUBECONFIG=$($dotenv get "HUB_KUBECONFIG")
if test -n "$HUB_KUBECONFIG" && test -f "$HUB_KUBECONFIG"; then
  KUBECONFIG="$HUB_KUBECONFIG"
  export KUBECONFIG
fi

if test -z "$HUB_TOKEN"; then
  STATEFILE=".hub/$HUB_DOMAIN_NAME.state";
  if test -f "$STATEFILE"; then
    RESP=$(hub explain "$STATEFILE" --json)
  else
    if test -z "$KUBECONFIG" -a -n "$HUB_KUBECONFIG"; then
      export KUBECONFIG=$HUB_KUBECONFIG
    fi
    kubectl="kubectl -n kube-system -o json"
    if ! $kubectl get configmap "superhub" > /dev/null 2>&1; then
      echo "Error: no stack deployed" 1>&2
      exit 5
    fi
    if test -z "$HUB_DOMAIN_NAME"; then
      HUB_DOMAIN_NAME=$( \
        $kubectl get configmap "superhub" \
        | jq -r '.data|keys[0]|select(.)'
      )
      if test -z "$HUB_DOMAIN_NAME"; then
        echo "Error: cannot find stack data" 1>&2
        exit 4
      fi
    fi
    RESP=$( \
      $kubectl get configmap "superhub" | \
      jq -r ".data[\"$HUB_DOMAIN_NAME\"] | select(.)" | \
      base64 -d
    )
  fi

else
  RESP=$(hub api instance get -j \
      | jq -S '. | if type=="array" then . else [.] end' \
      | jq -cMr '.[] | select(.domain=="'$HUB_DOMAIN_NAME'")')
fi


if test -z "$RESP"; then
    echo "Stack $HUB_DOMAIN_NAME not found" 1>&2
    exit 2
fi

if test ! -z "$RAW_OUTPUT"; then
  if test "$FORMAT" = "yaml"; then
    echo "$RESP" | yq r - 1>&2
  else
    echo "$RESP" | jq $JQ_ARGS . 1>&2
  fi
  exit 0
fi

to_obj() {
    echo "$1" | jq -cMr \
        'to_entries | .[]
            | {"key": .key | split(".") | reverse, "value": .value}
            | reduce .key[] as $item (.value; {($item): .})';
}

if test -n "$HUB_COMPONENT"; then
    if test -z "$HUB_TOKEN"; then
      if test "$(echo "$RESP" | jq -cMr '[.components|to_entries[] | .key] | index("'$HUB_COMPONENT'")')" == "null"; then
        echo "Cannot find \"$HUB_COMPONENT\" in components: $(echo "$RESP" | jq -cMr '[.components|to_entries[] | .key]') of \"$HUB_DOMAIN_NAME\"" 1>&2
        exit 3
      fi
      OUTPUTS=$(echo "$RESP" | jq -cMr '.components|to_entries[] | select(.key == "'$HUB_COMPONENT'").value | select(.outputs != null).outputs')
      PARAMETERS=$(echo "$RESP" | jq -cMr '.components|to_entries[] | select(.key == "'$HUB_COMPONENT'").value | select(.parameters != null).parameters')
    else
      if test "$(echo "$RESP" | jq -cMr '.componentsEnabled | index("'$HUB_COMPONENT'")')" == "null"; then
        echo "Cannot find \"$HUB_COMPONENT\" in components: $(echo "$RESP" | jq -cMr '.componentsEnabled') of \"$HUB_DOMAIN_NAME\"" 1>&2
        exit 3
      fi
      OUTPUTS=$(echo "$RESP" | jq -cMr '.status.components[] | select(.name == "'$HUB_COMPONENT'").outputs[] | {(.name):.value}')
      PARAMETERS=$(echo "$RESP" | jq -cMr 'select(.parameters).parameters[] | {(.name):.value}')
    fi
else
    if test -z "$HUB_TOKEN"; then
      PARAMETERS=$(echo "$RESP" | jq -cMr 'select(.stackParameters != null).stackParameters');
      OUTPUTS=$(echo "$RESP" | jq -cMr 'select(.stackOutputs != null).stackOutputs');
    else
      PARAMETERS=$(echo "$RESP" | jq -cMr 'select(.parameters).parameters[] | {(.name):.value}')
      OUTPUTS=$(echo "$RESP" | jq -cMr 'select(.outputs).outputs[] | {(.name):.value}')
    fi
fi

if test -n "$TRANSFORM"; then
    PARAMETERS=$(to_obj "$PARAMETERS");
    OUTPUTS=$(to_obj "$OUTPUTS");
fi
PARAMETERS=$(
  echo "$PARAMETERS" \
  | jq -cMs 'reduce .[] as $item ({}; . * $item) | to_entries | [ .[] | {"key": .key | split("|")[0], "value": .value}] | from_entries'
)
OUTPUTS=$( \
  echo "$OUTPUTS" \
  | jq -cMs 'reduce .[] as $item ({}; . * $item) | to_entries | [ .[] | {"key": .key | split("|")[0], "value": .value}] | from_entries'
)
if test ! -z "$SPLIT_OUTPUTS"; then
    DOCEXT="$(echo "$PARAMETERS" | jq -cM '{"parameters": .}')"
    DOCEXT="$DOCEXT $(echo "$OUTPUTS" | jq -cM '{"outputs": .}')"
else
    DOCEXT="$(echo "$PARAMETERS" | jq -cM '{"parameters": .}')"
    DOCEXT="$DOCEXT $(echo "$OUTPUTS" | jq -cM '{"parameters": .}')"
fi
if test -z "$HUB_TOKEN"; then
  if test -n "$(echo $RESP | jq -crM '.components|select(.)')"; then
    DOCBASE=$(echo $RESP | jq -crM '{
      "components" : [select(.components != null).components|to_entries[]|.key],
      "provides" : [select(.provides != null).provides|to_entries[]|.key]
    }')
  else
    # derive components from "provides"
    DOCBASE=$(echo $RESP | jq -crM '{
      "components" : [.provides|to_entries[].value|select(.)[]] | unique,
      "provides" : [select(.provides != null).provides|to_entries[]|.key]
    }')
  fi
else
  DOCBASE=$(echo $RESP | jq -crM '{
      "environment": .environment.name,
      "provides": [.provides|to_entries[]|.key],
      "components": .componentsEnabled,
      "state": .stateFiles[0],
      "template": .template.name,
      "tags": .tags
  }')
fi

if test "$FORMAT" = "yaml"; then
    echo "$DOCBASE" "$DOCEXT" | jq -cMs 'reduce .[] as $item ({}; . * $item) '"$JQ_QUERY" | yq r -
else
    echo "$DOCBASE" "$DOCEXT" | jq -cMs 'reduce .[] as $item ({}; . * $item) ' | jq $JQ_ARGS "$JQ_QUERY | select(.)"
fi
