#!/bin/bash -e
# shellcheck disable=SC2068,SC2086,SC2155

usage() {
  cat << EOF

Usage: $(basename "$0") checks if hub CLI infrastructure

Parameters:
    --aws-region          AWS Region
    --aws-profile         AWS Profile
    -s  --silent          Suppress console outputs in favor of result codes
    --skip-guide          Suppress "what's next" message
    -V --verbose          Provides verbosity for debug purposes
    -s  --silent          Suppress console outputs in favor of result codes
    --skip-guide          Suppress "What's next messages"
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message
EOF
}

SILENT=${SILENT:-false}
GUIDE=${GUIDE:-true}

# shellcheck disable=SC1091
test -f ".env" && source ".env"

while [ "$1" != "" ]; do
    case $1 in
        --aws-region )    shift
                          export AWS_REGION="$1"
                          ;;
        --aws-profile )   shift
                          export AWS_PROFILE="$1"
                          ;;
        -S | --silent )   SILENT=true
                          GUIDE=false
                          ;;
        --skip-guide  )   GUIDE=false
                          ;;
        -V | --verbose )  set -x
                          ;;
        -h | --help )     usage
                          exit
                          ;;
        * )               usage
                          exit 1
    esac
    shift
done

$SILENT || echo "Checking AWS account prerequisites:"
if test -f ".env"; then
  $SILENT || echo "* Configuration file .env exists: YES"
else
  $GUIDE && cat << EOF
* Configuration file .env exists: NO

***

To resolve please run: 

$ hub stack configure --current-kubecontext

EOF
  exit 2
fi

export AWS_DEFAULT_OUTPUT=text

bucket_exists() {
  aws s3api head-bucket --bucket="$1" 2>/dev/null
}

hosted_zone_exists() {
  test -n "$(aws route53 list-hosted-zones \
    --query 'HostedZones[?Name==`'$1'.`].Id' \
    | xargs | cut -d " " -f1)"
}


$SILENT || echo -n "* s3 bucket $HUB_STATE_BUCKET exists: "
SUCCESS=true
if bucket_exists "$HUB_STATE_BUCKET"; then
  $SILENT || echo "YES"
else 
  SUCCESS=false
  $SILENT || echo "NO"
fi

$SILENT || echo -n "* route53 hosted zone $HUB_DOMAIN_NAME exists: "
if hosted_zone_exists "$HUB_DOMAIN_NAME"; then
  $SILENT || echo "YES"
else 
  # shellcheck disable=SC2034
  SUCCESS=false
  $SILENT || echo "NO"
fi

if ! $SUCCESS; then 
  $GUIDE && cat << EOF

## What's next?

One or multiple prerequisites has not been deployed

To resolve, please run: 

$ hub ext aws init

EOF
  exit 3
fi

$GUIDE && cat << EOF

## What's next?

Your AWS infrastructure is up to date. Ready to run:

$ hub ext stack deploy

EOF
