#!/bin/bash -e

usage() {
  cat << EOF
Usage: hub stack <sub command>

Parameters:
    init            Initialize a brand new stack
    configure       Update stack configuration
    deploy          Deploy current stack
    undeploy        Undeploy current stack
    elaborate       Reconcile deployment plan for this stack
    explain         Display stack outputs, component's parameters, outputs, and capabilities
    backup          Backup operations
    invoke          Invoke stack component's verb
    ls              List of available stacks
    set             Setting active stack
EOF
}

usage
exit 1
