#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH

usage() {
cat << EOF

Display stack outputs, component's parameters, outputs, and capabilities.
Parameters and outputs are read from state file.

Usage:
$ $HUB_EXTENSION

Parameters:
    -l --op-log            Display operations log (only)
    -V  --verbose          Verbose outputs for debug purpose
    -h --help              Show this message

EOF
}

HUB_OPTS=
while [ "$1" != "" ]; do
    case $1 in
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    * )                 HUB_OPTS="$HUB_OPTS $1"
    esac
    shift
done

if test ! -f .env; then
    echo "* Error: configuration '.env' not found"
    exit 1
fi
eval "$(dotenv export -f "$HUB_WORKDIR/.env" )"

hub explain "$HUB_ELABORATE" "$HUB_STATE" $HUB_OPTS | less -R
