#!/bin/bash -e

usage() {
    cat << EOF

Undeploys Certified Stack from kuberentes cluster

Usage: 
$ $(basename "$0") -c component1,component2
Undeploys two components 

Parameters:
    -c --components       List of components to deploy
    -o --offset           Deploy starting with the given component
    -s  --silent          Suppress console outputs in favor of result codes
    -p --no-precheck      Skip `hub aws status` command execution
    -d --delete-toolbox   Deletes deployed toolbox 
    -k --keep-toolbox     Keeps toolbox deployed on kubernetes cluster
    --skip-guide          Suppress "What's next messages"
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message

EOF
}

undeploy_stack() {
    $SILENT || echo "Running undeploy stack from pod: ${K8S_PODNAME}"
    kubectl -n "$K8S_NAMESPACE" exec -it "${K8S_PODNAME}" -- bash -c "\
        source .env &&\
        hub stack elaborate &&\
        hub stack undeploy $@
        "
}


GUIDE=${GUIDE:-true}
SILENT=${SILENT:-false}
IMAGE=${IMAGE:-agilestacks/toolbox}
IMAGE_VERSION=${IMAGE_VERSION:-latest}
K8S_NAMESPACE=${K8S_NAMESPACE:-kube-system}
DELETE_TOOLBOX=${K8S_NAMESPACE:-true}
TOOLBOX_TIMEOUT=${TOOLBOX_TIMEOUT:-600}

while [ "$1" != "" ]; do
    case $1 in
        -p | --no-precheck ) 
                            CLOUD_CHECK=false
                            ;;
        -c | --component )  shift
                            HUB_DEPLOY_OPTS="$HUB_DEPLOY_OPTS -c $1"
                            FULL_STACK=false
                            CLOUD_CHECK=false
                            ;;
        -o | --offset )     shift
                            HUB_DEPLOY_OPTS="$HUB_DEPLOY_OPTS -o $1"
                            FULL_STACK=false
                            CLOUD_CHECK=false
                            ;;
        -k | --keep-toolbox ) 
                            DELETE_TOOLBOX=false
                            ;;
        -S | --silent )     SILENT=true
                            exit
                            ;;
        -V | --verbose )    set -x
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

export NOGUIDE SILENT IMAGE IMAGE_VERSION TOOLBOX_TIMEOUT 

# shellcheck disable=SC1091
source .env


if  test -z "${AWS_PROFILE}" && \
    test -x "$(which aws)" && \
    aws sts get-caller-identity > /dev/null 2>&1; then
    AWS_PROFILE=$(aws configure list | awk  '$1 ~ /^profile$/ {print $2}')
    export AWS_PROFILE
fi


hub ext remote --create-toolbox
export K8S_NAMESPACE=$(hub ext remote --get-namespace)
export K8S_PODNAME=$(hub ext remote --get-podname)
undeploy_stack
hub ext remote  --get-stack-state
$DELETE_TOOLBOX || hub ext remote --delete-toolbox
