#!/bin/bash -e

usage() {
  cat << EOF

Helper tool that dowloads components specified in hub.yaml
Use flags "-A" or "-C" to download all components or subset of them

Usage: 
$ $(basename "$0") -A -F 
To download all components and overwrite if they already exist

$ $(basename "$0") -F -C minio,tiller 
To download specified componenets and overwrite if they already exist


Parameters:
  -f  --file            Path to hub file (can repeat)
  -A  --all             All components
  -c  --component       Use only specific components defined in hub.yaml (can repeat)
  -F  --force           Downloads latest version of components even they exist
  -V  --verbose         Verbose outputs for debug purpose
  -h  --help            Print this message

EOF
}

# shellcheck disable=SC2086
local_dir() {
  local f res
  for f in $HUB_FILES; do
    res=$(
      yq r "$f" -j | \
      jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.dir'
    )
    test -z "$res" || break
  done
  echo "$res"
}

# shellcheck disable=SC2086
git_sub_dir() {
    local f res
    for f in $HUB_FILES; do
      res=$(
        yq r "$f" -j | \
        jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.subDir|select(.)'
      )
      test -z "$res" || break
    done
    echo "$res"
}

# shellcheck disable=SC2086
git_remote() {
  local f res
  for f in $HUB_FILES; do
    res=$(
      yq r "$f" -j | \
      jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.remote|select(.)'
    )
    test -z "$res" || break
  done
  echo "$res"
}

# shellcheck disable=SC2086
git_cloned_dir() {
  local f res
  for f in $HUB_FILES; do
    res=$(
      yq r "$f" -j | \
      jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.remote|select(.)|split("/")[-1] |split(".")[0]'
    )
    test -z "$res" || break
  done
  echo "$res"
}

# shellcheck disable=SC2086
git_ref() {
  local f res
  for f in $HUB_FILES; do
    res=$(
      yq r "$f" -j | \
      jq -r '.components?|select(.)[]|select(.name=="'$1'")|.source.git.ref|select(.)'
    )
    test -z "$res" || break
  done
  echo "$res"
}

if test -z "$*"; then
  usage
  exit 1
fi

dotenv=$(dirname "$0")/env/dotenv
if test -f ".env"; then
  set +a
  eval "$($dotenv export -f ".env" )"
  set -a
fi

CHECK=${CHECK:-true}
COMPONENT_JSON_PATH=${COMPONENT_JSON_PATH:-.hub/component_rev.json}
WORKDIR=${WORKDIR:-$(pwd)}
while [ "$1" != "" ]; do
    case $1 in
    -f | --file)        shift
                        if test ! -f "$1"; then
                          echo "Error: cannot find $1"
                          exit 1
                        fi
                        HUB_FILES=$(echo "$HUB_FILES $1" | xargs)
                        ;;
    -A | --all)         COMPONENTS=
                        ;; 
    --override)         CHECK=false
                        ;;
    -c | --component )  shift
                        COMPONENTS=$(echo "$COMPONENTS $1" | xargs)
                        ;;
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    * )                 usage
                        exit 1
    esac
    shift
done

if test -z "$HUB_FILES"; then
  echo "Error: cannot find hub files. Please run this command with --file flag"
  exit 1
fi

if test -z "$COMPONENTS"; then
  for f in $HUB_FILES; do
    c=$(yq r "$f" -j | jq -r '.components?|select(.)[]|select(.source.git != null ).name')
    COMPONENTS=$(echo "$COMPONENTS $c" | xargs)
    # GIT_URLS=$(yq r hub.yaml -j | jq -r '.components[].source.git.remote | select(length > 0)'  | sort | uniq)
  done
  if test -z "$COMPONENTS"; then
    echo "Error: cannot find components in [$HUB_FILES]"
  fi
fi

TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT
for component in $COMPONENTS; do
  echo -n "* Checking component $component: "
  to_dir=$(local_dir "$component")
  if test -d "$to_dir"; then
    echo "already exists"
    continue
  fi
  echo "fetching"
  remote=$(git_remote "$component")
  ref=$(git_ref "$component")
  sub_dir=$(git_sub_dir "$component")

  temp="$TEMP_DIR/$(echo "$remote+$ref" | sed 's/[^0-9a-zA-Z-]*//g')"
  if test ! -d "$temp"; then
    echo -n "  Cloning remote $remote ($ref): "
    git clone "$remote" "$temp" > /dev/null 2>&1
    git -C "$temp" checkout "$ref" > /dev/null 2>&1
    echo "done"
  fi
  echo -n "  Store to $to_dir: "
  mkdir -p "$(dirname $WORKDIR/$to_dir)"
  cp -rf "$temp/$sub_dir" "$WORKDIR/$to_dir"
  echo "Done"
done
