#!/bin/bash

pipe_to=bash

for arg in "$@"; do
case $arg in
    --help|-h)
        if which pygmentize >/dev/null; then
            cat='pygmentize -l md'
        else
            cat=cat
        fi
        $cat $(dirname $0)/hub-pull.md
        exit 0
        ;;

    --show|-s)
        if which pygmentize >/dev/null; then
            pipe_to='pygmentize -l bash'
        else
            pipe_to=cat
        fi
        shift
        ;;

    --debug|-d|--trace|-t) # compat
        shift
        ;;
esac
done

set -o pipefail

exec node $(dirname $0)/hub-pull.js "$@" | $pipe_to
