#!/bin/bash -e

usage()
{
    echo "Show stack secret"
    echo "usage:"
    echo "hub ext show-secret [-s domain-name] [-r secret-reference]"
    echo 
    echo "Example:"
    echo "export STACK=abc.superhub.io; hub show -q '.parameters.component.docker.auth.basic.password' | hub-show-secret"
    exit 0
}

if ! test -t 0; then
    REF=$(cat /dev/stdin | xargs | cut -d " " -f1 | tr -d '"')
fi

while [ "$1" != "" ]; do
    case $1 in
        -s | --stack )      shift
                            STACK=$1
                            ;;
        -r | --secret-ref ) shift
                            REF=$(echo $1 | tr -d '"')
                            ;;                            
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

if test -z "$STACK" || test -z "$REF"; then
    usage;
    exit 1
fi

hub api instance secret get $STACK $REF
