#!/bin/bash -e

usage() {
  cat << EOF
Remove IAM policy from EKS cluster

Usage: $(basename "$0") -c lorem-ipsum --all

Usage: $(basename "$0") -c lorem-ipsum -p AmazonS3FullAccess

Parameters:
    -c --eks-cluster      Name of the eks cluster (required)
    --aws-region          AWS Region
    --aws-profile         AWS Profile
    -V  --verbose         Verbose outputs for debug purpose
EOF
}

test -f ".env" && source .env

ALL_POLICIES=false
POLICY_NAME="$CLUSTER_NAME-custompolicy"

while [ "$1" != "" ]; do
  case $1 in
    -c | --eks-cluster ) shift
                         CLUSTER_NAME="$1"
                         ;;
    -p | --policy )      shift
                         POLICY_NAME="$1"
                         ;;
    --aws-region )       shift
                         export AWS_REGION="$1"
                         ;;
    --aws-profile )      shift
                         export AWS_PROFILE="$1"
                         ;;
    -V | --verbose )     set -x
                         ;;
    -h | --help )        usage
                         exit
                         ;;
    * )                  usage
                         sexit 1
  esac
  shift
done

if test -z "$CLUSTER_NAME"; then
  usage
  exit 1
fi

export AWS_DEFAULT_OUTPUT=text

ROLE_ARN=$(eksctl get iamidentitymapping --cluster "$CLUSTER_NAME" -o json | jq -r '.[0].rolearn')
if test -n "$ROLE_ARN"; then
  aws iam list-attached-role-policies \
      --role-name "$(basename $ROLE_ARN)" \
      --query 'AttachedPolicies[].PolicyName'
fi
