#!/bin/bash -e
# shellcheck disable=SC2086

usage() {
cat << EOF

Deploys this stack

Usage: 
$ $(basename "$0")

Deploys all components

$ $(basename "$0") -c component1,component2
Deploys deploys two components 

Parameters:
    -c --component        List of components to deploy
    --profile             Can be: deploy-pod (default) | deploy-local | deploy-toolbox    
    -o --offset           Deploy starting with the given component
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message

EOF
}

dotenv=$(dirname "$0")/env/dotenv
set +a
eval "$($dotenv export -f ".env" )"
set -a

while [ "$1" != "" ]; do
    case $1 in
        --profile )         shift
                            HUB_DEPLOY_PROFILE="$1"
                            ;;   
        -c | --component )  shift
                            HUB_OPTS="$HUB_OPTS -c $1"
                            ;;
        -o | --offset )     shift
                            HUB_OPTS="$HUB_OPTS -o $1"
                            ;;
        -V | --verbose )    set -x
                            export HUB_TRACE=1
                            export HUB_DEBUG=1
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

if ! test -f .env; then
  cat << EOF
Error: .env file has not been found 
Please run:

  $ hub configure

EOF
  exit 1
fi

HUB_FILES=$($dotenv get "HUB_FILES")
HUB_ELABORATE_FILE="${HUB_ELABORATE_FILE:-".hub/$HUB_DOMAIN_NAME.elaborate"}"
HUB_STATE_FILE="${HUB_STATE_FILE:-".hub/$HUB_DOMAIN_NAME.state"}"
HUB_OPTS="--force --clouds=aws $HUB_OPTS"

cat << EOF
Undeploying: $HUB_DOMAIN_NAME"

Warning: this operation cannot be reverted! It may lead to data loss!

EOF

echo "* Using cluster: $HUB_DOMAIN_NAME"
if ! test -f "$HUB_ELABORATE_FILE"; then
  echo "Error: cannot find hub elaborate file: $HUB_ELABORATE_FILE"
  exit 2
fi

echo "* Using hub elaborate file: $HUB_ELABORATE_FILE"

if test -f "$HUB_STATE_FILE"; then
  HUB_OPTS="$HUB_OPTS -s $HUB_STATE_FILE"
  echo "* Using hub state file: $HUB_STATE_FILE"  
fi

cat <<EOF

### Proceeding with undeploy "$HUB_DOMAIN_NAME"

EOF

if test -z "$HUB_DEPLOY_PROFILE"; then
  HUB_DEPLOY_PROFILE=$($dotenv get "HUB_DEPLOY_PROFILE")
  if test -z "$HUB_DEPLOY_PROFILE"; then
    HUB_DEPLOY_PROFILE="pod"
  fi
fi
if test ! -f "$(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/undeploy"; then
  echo "Warning: $(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/undeploy not found!"
  echo "Falling back to $(dirname "$0")/profiles/local/undeploy"
  HUB_DEPLOY_PROFILE="local"
fi

for f in $HUB_FILES; do
  test -f "$f" || continue;
  AFTER="$AFTER $(yq r "$f" -j | jq -r '.extensions.undeploy.before? | select(.)[]')"
done
if test -n "$AFTER"; then
  echo "Running post deployment extensions: $AFTER"
  for i in $(echo "$AFTER" | xargs -n1); do
    if test -f "$(dirname "$0")/$i/before-undeploy"; then
      "$(dirname "$0")/$i/before-undeploy"
    fi
  done
fi

# shellcheck disable=SC2086,SC2046
$(dirname "$0")/profiles/$HUB_DEPLOY_PROFILE/undeploy \
  "$HUB_ELABORATE_FILE" \
  -s "$HUB_STATE_FILE" \
  $HUB_OPTS

for f in $HUB_FILES; do
  test -f "$f" || continue;
  AFTER="$AFTER $(yq r "$f" -j | jq -r '.extensions.undeploy.after? | select(.)[]')"
done
if test -n "$AFTER"; then
  echo "Running post deployment extensions: $AFTER"
  for i in $(echo "$AFTER" | xargs -n1); do
    if test -f "$(dirname "$0")/$i/after-undeploy"; then
      "$(dirname "$0")/$i/after-undeploy"
    fi
  done
fi
