#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.


HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
HUB_EXTENSION="$(basename "$0" | sed -e 's/hub-/hubctl /g' -e 's/-/ /g')"

usage() {
  cat << EOF
Use or change currently active stack

Usage: $HUB_EXTENSION STACK

  where STACK is the name of the stack to use as an active

Note: to see list of available stacks run

  $ hubctl stack ls

EOF
}

if test -z "$1"; then
  usage
  exit 1
fi

if test "$1" = "initialized"; then
  dotfile="$HUB_WORKDIR/.hub/env/.env"
else
  dotfile="$HUB_WORKDIR/.hub/env/$1.env"
fi

if test ! -d "$HUB_WORKDIR/.hub/env"; then
  color error "Error: no stacks available"
  exit 2
fi

echo "Using $1 as current"
if test ! -f "$dotfile"; then
  color error "Error: cannot find $1 stack"
  cat << EOF

To see list of available stacks run

  $ hubctl stack ls

EOF
  exit 3
fi


if test -L "$HUB_WORKDIR/.env"; then
  echo "* Unlinking .env"
  unlink "$HUB_WORKDIR/.env"
elif test -f "$HUB_WORKDIR/.env"; then
  echo "* Backing up .env as .env.bak"
  mv "$HUB_WORKDIR/.env" "$HUB_WORKDIR/.env.bak"
fi

if test ! -f "$HUB_WORKDIR/.env"; then
  echo "* Setting .env link to $1"
  ln -sf "$dotfile" "$HUB_WORKDIR/.env"
fi
