#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


set -o pipefail

HUB=${HUB:-hub}
domain=$1
parameter=$2
value=$3

test -n "$domain" -a -n "$parameter"
# TODO jq to add parameter if missing
$HUB api instance get -j "$domain" |
    jq "{parameters: [.parameters[] | (select(.name == \"${parameter}\")) += {value: \"${value}\"}]}" |
    $HUB api instance patch "$domain"
