#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# shellcheck disable=SC2068

usage() {
  cat << EOF

Usage: $(basename "$0") <sub command>

EKS cluster node group IAM policies

Sub commands:
    attach   Attach IAM policy
    detach   Detach IAM policy
    ls       List IAM policies

EOF
}

if test -z "$1"; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
  case $1 in
    attach )      hub-eks-policy-attach "$@"
                  ;;
    detach )      hub-eks-policy-attach "$@"
                  ;;
    ls     )      hub-eks-policy-ls "$@"
                  ;;
    -h | --help ) usage
                  exit
                  ;;
    * )           usage
                  exit 1
  esac
  shift
done
