#!/bin/sh -e
# Copyright (c) 2022 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
HUB_MANUAL_ELABORATE="${HUB_MANUAL_ELABORATE:-"1"}"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH HUB_WORKDIR
DOT_ENV="$(files abspath .env)"
export DOT_ENV

usage() {
cat << EOF
Runs a toolbox as a container and mounts current working directory

Usage:
  $HUB_EXTENSION [DOMAIN_NAME]

Parameters:
    -i  --toolbox-image ARG  Toolbox docker image (default: HUB_TOOLBOX_IMAGE and agilestacks/toolbox:stable)
    -V  --verbose            Verbose outputs for debug purpose
    -h --help                Show this message

EOF
}

TOOLBOX_SHELL="${TOOLBOX_SHELL:-"/bin/bash"}"

while [ "$1" != "" ]; do
    case $1 in
    -i | --toolbox-image)
        shift
        HUB_TOOLBOX_IMAGE="$1"
    ;;
    -V | --verbose )
        set -x
    ;;
    -h | --help )
        usage
        exit
    ;;
    * )
        usage
        exit 1
    ;;
    esac
    shift
done

if test -z "$USER"; then
    color err "Error: variable USER has not been defined"
    exit 1
fi

if test -z "$HOME"; then
    color err "Error: variable HOME has not been defined"
    exit 1
fi

if test "$HUB_WORKDIR" = "/"; then
    color err "Errror: cannot mount root (/) directory inside container"
    exit 1
fi

if test -z "$HUB_TOOLBOX_IMAGE"; then
    HUB_TOOLBOX_IMAGE=$(dotenv get "HUB_TOOLBOX_IMAGE" --default "docker.io/agilestacks/toolbox:stable")
fi

finalize() {
  # shellcheck disable=SC2046
  rv=$1

  rm -rf "$envfile" "$pruned_docker_config_dir"

  # shellcheck disable=SC2086
  exit $rv
}

if test -z "$HUB_WORKDIR"; then
  FIRST_FILE="$(echo "$HUB_FILES" | awk '{print $1;}')"
  if test -f $FIRST_FILE; then
    HUB_WORKDIR=$(dirname "$FIRST_FILE")
  else
    HUB_WORKDIR=$(pwd)
  fi
fi

if  test -z "${AWS_PROFILE}" && \
    test -x "$(which aws)" && \
    aws sts get-caller-identity > /dev/null 2>&1; then
    AWS_PROFILE=$(aws configure list | awk  '$1 ~ /^profile$/ {print $2}')
    export AWS_PROFILE
fi

envfile=$(mktemp)
env | grep -E '^(AWS_|GOOGLE_|AZURE_|HUB_CRYPTO_|TF_|TERM=|LANG=|LC_)' >"$envfile"
envadd=""
if test -s "$envfile"; then
    envadd="--env-file $envfile"
fi

trap 'finalize $?' EXIT

docker_config="$HOME/.docker/config.json"
if test -f $docker_config && grep -E '(osxkeychain|desktop)"' $docker_config >/dev/null; then
    pruned_docker_config_dir=$(mktemp -d /tmp/docker.XXXXXX)
    sed -E -e 's/(osxkeychain|desktop)"/"/g' $docker_config > $pruned_docker_config_dir/config.json
    maybe_docker_config="-v $pruned_docker_config_dir:$HOME/.docker"
fi

if test -e /var/run/docker.sock; then
    maybe_docker_socket="-v /var/run/docker.sock:/var/run/docker.sock"
fi

# direnv hook is strictly for interactive shell
# ask direnv to set environment explicitly to allow
#   $ hubctl toolbox make deploy
if test $# -gt 0 -a -n "$TOOLBOX_DIRENV"; then
    args="direnv exec . $*"
fi

docker run -ti --rm \
    -h toolbox-"$(tty|sed -e 's|/dev/||')" \
    -e TMPDIR=/tmp \
    -e "USER=$USER" \
    -e "UID=$(id -u)" \
    -e "GID=$(id -g)" \
    -e "HOME=$HOME" \
    -e "SHELL=${TOOLBOX_SHELL}" \
    -e 'PS1=\u@\e[92m\h\e[0m \w $ ' \
    -v "$HOME:$HOME" \
    -v "$HUB_WORKDIR:$HUB_WORKDIR" \
    $maybe_docker_socket \
    $maybe_docker_config \
    --privileged=true \
    --cap-add=NET_ADMIN \
    -w "$HUB_WORKDIR" \
    "$HUB_TOOLBOX_IMAGE" \
    $envadd $args
