#!/bin/bash -e

usage() {
cat << EOF

Runs reconciliation for all parameters of this stack components
and this stack prerequisites

Usage:
$ hub stack deploy

Parameters:
    -V  --verbose          Verbose outputs for debug purpose
    -h --help              Show this message

EOF
}

HUB_OPTS=
while [ "$1" != "" ]; do
    case $1 in
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    * )                 usage
                        exit 1
    esac
    shift
done

echo "Reconciling deployment plan for $HUB_DOMAIN_NAME"

if [[ ! -f .env ]]; then
  echo "* Error: configuration '.env' has not been found"
  exit 1
fi
dotenv=$(dirname "$0")/env/dotenv
set +a
eval "$($dotenv export -f ".env" )"
set -a
echo "* Using domain name: $HUB_DOMAIN_NAME"

if test -z "$HUB_FILES"; then
  cat << EOF
Error: cannot find hub definition files (HUB_FILES)"

Probably because stack has not been configured for deployment yet!

Example:
  $ hub configure -f hub.yaml

EOF

  exit 2
fi

if test -z "$HUB_STATE"; then
  if test -f ".hub/$HUB_DOMAIN_NAME.state"; then
    HUB_STATE=".hub/$HUB_DOMAIN_NAME.state"
  fi
fi

# if test -n "$HUB_STATE"; then
#   echo "* Using hub state: $HUB_STATE"
#   HUB_OPTS="$HUB_OPTS -s $HUB_STATE"
# fi

if test -z "$HUB_ELABORATE"; then
  HUB_ELABORATE=".hub/$HUB_DOMAIN_NAME.elaborate"
fi

cat << EOF

Proceeding with: elaborate
* Result will be saved saved to: $HUB_ELABORATE
* Running CLI command:

  $ hub elaborate $HUB_FILES -o $HUB_ELABORATE $HUB_OPTS

EOF

# shellcheck disable=SC2086
hub elaborate $HUB_FILES -o "$HUB_ELABORATE" $HUB_OPTS
