#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


usage() {
  cat << EOF
List EKS cluster nodegroup IAM role policies

Usage:
    $(basename "$0") -c cluster-name

Parameters:
    -c --eks-cluster      Name of the eks cluster (required)
    --aws-region          AWS Region
    --aws-profile         AWS Profile
    -V  --verbose         Verbose outputs for debug purpose
EOF
}

test -f ".env" && source .env

while [ "$1" != "" ]; do
  case $1 in
    -c | --eks-cluster ) shift
                         CLUSTER_NAME="$1"
                         ;;
    --aws-region )       shift
                         export AWS_REGION="$1"
                         ;;
    --aws-profile )      shift
                         export AWS_PROFILE="$1"
                         ;;
    -V | --verbose )     set -x
                         ;;
    -h | --help )        usage
                         exit
                         ;;
    * )                  usage
                         exit 1
  esac
  shift
done

if test -z "$CLUSTER_NAME"; then
  usage
  exit 1
fi

export AWS_DEFAULT_OUTPUT=text

ROLE_ARN=$(eksctl get iamidentitymapping --cluster "$CLUSTER_NAME" -o json | jq -r '.[0].rolearn')
if test -n "$ROLE_ARN"; then
  (for NAME in $(aws iam list-attached-role-policies \
                  --role-name "$(basename $ROLE_ARN)" \
                  --query 'AttachedPolicies[].PolicyName'); do
    echo "$NAME"
  done) | sort
fi
