#!/bin/sh -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

profile="$1"
verb="$2"
shift
test -n "$profile" -a -n "$verb"
dir=$(dirname "$0")/profiles/$profile
impl=$dir/impl
if test -x "$dir/$verb"; then
    shift
    impl=$dir/$verb
fi
exec "$impl" "$@"
