#!/bin/bash -e

usage() {
  cat << EOF
Usage: hub stack <sub command>

Management commands:
    init            Initialize a brand new stack
    configure       Update stack configuration
    ls              List of available stacks
    set             Setting active stack
    rm              Delete current stack configuration

Deployment commands:
    deploy          Deploy current stack
    undeploy        Undeploy current stack
    backup          Backup operations
    invoke          Invoke stack component's verb
    elaborate       Reconcile deployment plan for this stack
EOF
}

usage
exit 1
