#!/bin/bash -e

usage() {
cat << EOF

Deploys this stack

Usage: 
$ $(basename "$0")

Deploys all components

$ $(basename "$0") -c component1,component2
Deploys deploys two components 

Parameters:
    -c --components       List of components to deploy
    -t --with-toollbox    Use toolbox image to run deployment 
                          also enabled by setting HUB_TOOLBOX to non empty
    -o --offset           Deploy starting with the given component
    -s  --silent          Suppress console outputs in favor of result codes
    -p --no-precheck      Skip `hub ext aws status` command execution 
    --skip-guide          Suppress "What's next messages"
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message

EOF
}

FULL_STACK=true
GUIDE=${GUIDE:-true}
SILENT=${SILENT:-false}
CLOUD_CHECK=true

while test "$1" != ""; do
    case $1 in
        -t | --with-toollbox  ) 
                            HUB_TOOLBOX="1"
                            ;;
        -p | --no-precheck ) 
                            CLOUD_CHECK=false
                            ;;
        -c | --component )  shift
                            HUB_DEPLOY_OPTS="$HUB_DEPLOY_OPTS -c $1"
                            FULL_STACK=false
                            CLOUD_CHECK=false
                            ;;
        -o | --offset )     shift
                            HUB_DEPLOY_OPTS="$HUB_DEPLOY_OPTS -o $1"
                            FULL_STACK=false
                            CLOUD_CHECK=false
                            ;;
        -S | --silent )     SILENT=true
                            exit
                            ;;
        -V | --verbose )    set -x
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

if test ! -f .env; then
cat << EOF
Configuration has not been found. To resolve please run:

$ hub configure --current-kubecontext

EOF
  exit 1
fi
# shellcheck disable=SC1091
source .env

cat << EOF
Starting deployment:
* Using domain name: $HUB_DOMAIN_NAME
* Using kubeconfig: $KUBECONFIG

EOF

if $CLOUD_CHECK; then
  set +e
  hub ext aws status --skip-guide
  hub_aws_rv="$?"
  set -e
fi

if test "$hub_aws_rv" = "2"; then
  cat << EOF
Error: Cannot find .env configuration. Please run:

$ hub ext configure --current-kubeconfig

EOF
  exit "$hub_aws_rv"

elif test "$hub_aws_rv" = "3"; then
  hub ext aws init --skip-guide
fi

HUB_ELABORATE_FILE="${HUB_ELABORATE_FILE:-".hub/$HUB_DOMAIN_NAME.elaborate"}"
HUB_STATE_FILE="${HUB_STATE_FILE:-".hub/$HUB_DOMAIN_NAME.state"}"

if test -f "$HUB_STATE_FILE"; then
  HUB_ELABORATE_OPTS="$HUB_ELABORATE_OPTS -s $HUB_STATE_FILE"
fi

if test -n "$CLOUD_PROVIDER"; then
  HUB_DEPLOY_OPTS="--clouds=$CLOUD_PROVIDER $HUB_DEPLOY_OPTS"
fi

# shellcheck disable=SC2086
if $FULL_STACK || test ! -f "$HUB_ELABORATE_FILE"; then
  hub ext stack elaborate --skip-guide
fi

# shellcheck disable=SC2086
if test -n "$HUB_TOOLBOX"; then
  hub ext toolbox \
    /bin/bash -c "
    . .env; \
    hub deploy $HUB_ELABORATE_FILE -s $HUB_STATE_FILE $HUB_DEPLOY_OPTS;
    "
else
  hub deploy "$HUB_ELABORATE_FILE" -s "$HUB_STATE_FILE" $HUB_DEPLOY_OPTS
fi
