#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


usage() {
    cat << EOF
Usage: $(basename "$0") <sub command>

Parameters:
    download          Downloads stack componenets
    list              List downloaded stack componenets

EOF
}

if test -z "$*"; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
  cmd=$1
  shift
  case $cmd in
    download )          $HUB ext component download $@
                        ;;
    list )              $HUB ext component list $@
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    * )                 usage
                        exit 1
  esac
done




