#!/bin/bash
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


pipe_to=bash

for arg in "$@"; do
case $arg in
    --help|-h)
        if which pygmentize >/dev/null; then
            cat='pygmentize -l md'
        else
            cat=cat
        fi
        $cat $(dirname $0)/hub-pull.md
        exit 0
        ;;

    --show|-s)
        if which pygmentize >/dev/null; then
            pipe_to='pygmentize -l bash'
        else
            pipe_to=cat
        fi
        ;;
esac
done

set -o pipefail

exec node $(dirname $0)/hub-pull.js "$@" | $pipe_to
