#!/bin/bash -e
HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH

if [[ ! -f .env ]]; then
  echo "* Error: configuration '.env' has not been found"
  exit 1
fi
eval "$(dotenv export -f ".env" )"

if test -z "$HUB_BACKUP_DIR"; then
  HUB_BACKUP_DIR=".hub/backups"
fi

find_tags() {
  local param
  param="$(files abspath "$1")"
  for f in $HUB_BACKUP_DIR/tags/*; do
    if ! test -L "$f"; then continue; fi
    if test "$(files abspath "$(readlink -n "$f")")" = "$param"; then
      echo -n " $(basename "$f")"
    fi
  done
}

if test -L "$HUB_BACKUP_DIR/$HUB_DOMAIN_NAME/.elaborate"; then
  elaborated="$(files abspath "$(readlink -n "$HUB_BACKUP_DIR/$HUB_DOMAIN_NAME/.elaborate")")"
fi

working_dir="$HUB_BACKUP_DIR/$HUB_DOMAIN_NAME"
if test -d "$working_dir"; then
  cat << EOF

Listing backups for $HUB_DOMAIN_NAME:
EOF
  for d in "$working_dir"/*; do
    if test ! -d "$d"; then continue; fi
    tags="$(find_tags "$d")"
    if test "$elaborated" == "$(files abspath "$d")"; then
      star="*"
    else
      star=" "
    fi
    if test -z "$tags"; then
      echo "$star $(basename "$d")    local"
    else
      echo "$star $(basename "$d")    local    $(echo "$tags" | xargs)"
    fi
  done
else
  echo "There are no backups for stack $HUB_DOMAIN_NAME"
  exit 2
fi
