#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.

HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH

usage() {
cat << EOF

Create backup for current stack

Parameters:
    -t --tag              Backup tags
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message

Usage:

    hubctl stack backup tag BACKUP_NAME -t TAG_NAME

EOF
}

if test -z "$1"; then
  usage
  exit 1
fi

if test ! -f "$HUB_WORKDIR/.env"; then
  color error "Error: cannot find .env file in $HUB_WORKDIR"
  exit 1
fi
eval "$(dotenv export -f "$HUB_WORKDIR/.env")"

if test -z "$HUB_DOMAIN_NAME"; then
  color error "Error: HUB_DOMAIN_NAME has not been defined"
  exit 2
fi

while test "$1" != ""; do
    case $1 in
        -t | --tag )        shift
                            HUB_BACKUP_TAG="$1"
                            ;;
        -V | --verbose )    set -x
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 HUB_BACKUP_NAME=$1
    esac
    shift
done


if test -z "$HUB_BACKUP_NAME"; then
  color error "Error: name of the bakcup is missing"
  usage
  exit 2
fi

if test -z "$HUB_DOMAIN_NAME"; then
  color error "Error: HUB_DOMAIN_NAME has not been defined"
  exit 2
fi

if test -z "$HUB_BACKUP_DIR"; then
  HUB_BACKUP_DIR="$HUB_WORKDIR/.hub/backups"
else
  HUB_BACKUP_DIR=$(files abspath "$HUB_BACKUP_DIR")
fi

if test -z "$HUB_BACKUP_TAG"; then
  color error "Error: backup tag has not been defined"
  usage
  exit 4
fi

backup_path="$HUB_BACKUP_DIR/$HUB_DOMAIN_NAME/$HUB_BACKUP_NAME"
tag_path="$HUB_BACKUP_DIR/tags/$HUB_BACKUP_TAG"
if test ! -d "$backup_path"; then
  color error "Error: directory $backup_path not found"
  exit 3
fi

echo "* Setting tag: $HUB_BACKUP_TAG..."
if test -L "$tag_path"; then
  echo "  Unlinking $tag_path"
  unlink "$tag_path"
fi
echo "  Reference to bakup: $(basename "$backup_path")"
mkdir -p "$(dirname "$tag_path")"
ln -s "$backup_path" "$tag_path"
