#!/bin/sh -e

if test -z "$USER"; then
    echo USER is not set
    exit 1
fi

if test -z "$HOME"; then
    echo HOME is not set
    exit 1
fi

BASEDIR="$(pwd)"
if test "$BASEDIR" = "/"; then
    echo "Toolbox doesn't support '/' as current directory"
    exit 1
fi

TOOLBOX_SHELL=${TOOLBOX_SHELL:-/bin/bash}
IMAGE=${IMAGE:-agilestacks/toolbox}
IMAGE_VERSION=${IMAGE_VERSION:-stable}

if  test -z "${AWS_PROFILE}" && \
    test -x "$(which aws)" && \
    aws sts get-caller-identity > /dev/null 2>&1; then
    AWS_PROFILE=$(aws configure list | awk  '$1 ~ /^profile$/ {print $2}')
    export AWS_PROFILE
fi

envfile=$(mktemp)
env | grep -E '^(AWS_|GOOGLE_|AZURE_|TF_|TERM=|LANG=|LC_)' >"$envfile"
envadd=""
if test -s "$envfile"; then
    envadd="--env-file $envfile"
fi

docker_config=$HOME/.docker/config.json
if test -f $docker_config && grep -E '(osxkeychain|desktop)"' $docker_config >/dev/null; then
    pruned_docker_config_dir=$(mktemp -d /tmp/docker.XXXXXX)
    sed -E -e 's/(osxkeychain|desktop)"/"/g' $docker_config > $pruned_docker_config_dir/config.json
    maybe_docker_config="-v $pruned_docker_config_dir:$HOME/.docker"
fi

if test -e /var/run/docker.sock; then
    maybe_docker_socket="-v /var/run/docker.sock:/var/run/docker.sock"
fi

# direnv hook is strictly for interactive shell
# ask direnv to set environment explicitly to allow
#   $ hub toolbox make deploy
if test $# -gt 0 -a -n "$TOOLBOX_DIRENV"; then
    args="direnv exec . $*"
fi

docker run -ti --rm \
    -h toolbox-"$(tty|sed -e 's|/dev/||')" \
    -e TMPDIR=/tmp \
    -e "USER=$USER" \
    -e "UID=$(id -u)" \
    -e "GID=$(id -g)" \
    -e "HOME=$HOME" \
    -e "SHELL=${TOOLBOX_SHELL}" \
    -e 'PS1=\u@\e[92m\h\e[0m \w $ ' \
    -v "$HOME:$HOME" \
    -v "$BASEDIR:$BASEDIR" \
    $maybe_docker_socket \
    $maybe_docker_config \
    --privileged=true \
    --cap-add=NET_ADMIN \
    -w "$BASEDIR" \
    $envadd \
    "$IMAGE:$IMAGE_VERSION" $args

rm -f $envfile $pruned_docker_config
