#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.

HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH

usage() {
cat << EOF

Create backup for current stack

Parameters:
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message

Usage:

    hubctl stack backup tag TAG_NAME

EOF
}

if test -z "$1"; then
  usage
  exit 1
fi


while test "$1" != ""; do
    case $1 in
        -V | --verbose )    set -x
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 HUB_BACKUP_TAG="$1"
    esac
    shift
done


if test -z "$HUB_BACKUP_TAG"; then
  color error "Error: tag name is missing"
  usage
  exit 2
fi

if test ! -f "$HUB_WORKDIR/.env"; then
  color error "Error: cannot find .env file in $HUB_WORKDIR"
  exit 1
fi
eval "$(dotenv export -f "$HUB_WORKDIR/.env")"

if test -z "$HUB_BACKUP_DIR"; then
  HUB_BACKUP_DIR="$HUB_WORKDIR/.hub/backups"
else
  HUB_BACKUP_DIR=$(files abspath "$HUB_BACKUP_DIR")
fi

tag_path="$HUB_BACKUP_DIR/tags/$HUB_BACKUP_TAG"
if test ! -L "$tag_path"; then
  color error "Error: $HUB_BACKUP_TAG not found"
  exit 3
fi

echo "Unlinking $HUB_BACKUP_TAG"
unlink "$tag_path"
