#!/bin/bash -e

usage() {
  cat << EOF
Usage: hub stack <sub command>

Management commands:
    init            Initialize a brand new stack
    configure       Update stack configuration
    deploy          Deploy current stack
    undeploy        Undeploy current stack
    ls              List of available stacks
    set             Setting active stack
    unconfigure     Delete current stack configuration

Deployment commands:
    elaborate       Reconcile deployment plan for this stack
    explain         Display stack outputs, component's parameters, outputs, and capabilities
    backup          Backup operations
    invoke          Invoke stack component's verb
EOF
}

usage
exit 1
