#!/bin/bash -e

HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH

usage() {
cat << EOF
Remove configuration from current stack

Usage:
$ hub stack unconfigure [DOMAIN_NAME]

Parameters:
    -V  --verbose          Verbose outputs for debug purpose
    -h --help              Show this message

EOF
}

if test -f ".env"; then
  DOTENV=".env"
elif test -L ".env"; then
  DOTENV=$(readlink ".env")
fi

while [ "$1" != "" ]; do
    case $1 in
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    * )                 DOTENV=".hub/env/$1.env"
                        ;;
    esac
    shift
done

if test ! -f "$DOTENV"; then
  cat <<EOF
* Error: configuration '.env' has not been found"

EOF
  usage
  cat <<EOF

To see list of available stacks run

  $ hub stack ls

EOF
  exit 1
fi
dotenv="dotenv -f $DOTENV"
HUB_DOMAIN_NAME="$($dotenv get "HUB_DOMAIN_NAME")"
if test -z "$HUB_DOMAIN_NAME"; then
  echo "Error: 'HUB_DOMAIN_NAME' has not been defined!"
  echo "Error:  is $DOTENV is a stack you want to unconfigure?"
  exit 2
fi

echo "Unconfiguring: $HUB_DOMAIN_NAME"

FILES=$(ls .hub/env/$HUB_DOMAIN_NAME.*)
FILES="$FILES $($dotenv get "HUB_STATE" | sed "s/,/ /g")"
FILES="$FILES $($dotenv get "HUB_ELABORATE" | sed "s/,/ /g")"
FILES="$FILES $DOTENV"
for f in $FILES; do
  test -f "$f" || continue
  echo "* Removing $f"
  rm -f "$f"
done

if test -L ".env"; then
  envfile=$(readlink ".env")
  if "$envfile" -ef ".env"; then
    echo "* Removing .env: "
    unlink ".env"
  fi
fi

echo "Unconfigured!"
