#!/bin/bash -e

HUB_HOME="${HUB_HOME:-$(dirname "$0")}"
HUB_WORKDIR="${HUB_WORKDIR:-$(pwd)}"
HUB_EXTENSION="$(basename "$0" | sed 's/-/ /g')"
PATH="$HUB_HOME:$HUB_HOME/bin:$HUB_WORKDIR:$HUB_WORKDIR/bin:$PATH"
export PATH HUB_WORKDIR

usage() {
cat << EOF
Remove configuration from current stack

Usage:
$ $HUB_EXTENSION [DOMAIN_NAME]

Parameters:
    -V  --verbose          Verbose outputs for debug purpose
    -h --help              Show this message

EOF
}

if test -f ".env"; then
  DOT_ENV=".env"
elif test -L ".env"; then
  DOT_ENV=$(readlink ".env")
fi

while [ "$1" != "" ]; do
    case $1 in
    -V | --verbose )    set -x
                        ;;
    -h | --help )       usage
                        exit
                        ;;
    initialized )       DOT_ENV=".hub/env/.env"
                        ;;
    * )                 DOT_ENV=".hub/env/$1.env"
                        ;;
    esac
    shift
done

if test -L "$HUB_WORKDIR/.env" -a ! -e "$HUB_WORKDIR/.env"; then
  echo "* Unlinking: .env"
  unlink "$HUB_WORKDIR/.env"
  exit
fi

if test ! -f "$DOT_ENV"; then
  cat <<EOF
* Nothing to remove

EOF
  usage
  cat <<EOF

To see list of available stacks run

  $ hub stack ls

EOF
  exit 1
fi
dotenv="dotenv -f $DOT_ENV"
HUB_DOMAIN_NAME="$($dotenv get "HUB_DOMAIN_NAME")"
if test -z "$HUB_DOMAIN_NAME"; then
  HUB_DOMAIN_NAME="$($dotenv get "HUB_STACK_NAME" --default "initialized")"
  if test -L .env; then
    FILES="$FILES $(readlink -n .env)"
  fi
fi

if test -n "$HUB_DOMAIN_NAME"; then
  # shellcheck disable=SC2086
  FILES=$(ls .hub/env/$HUB_DOMAIN_NAME.*)
else
  FILES="$(ls .hub/env/.env)"
fi

echo "Unconfiguring: $HUB_DOMAIN_NAME"
FILES="$FILES $($dotenv get "HUB_STATE" | sed "s/,/ /g")"
FILES="$FILES $($dotenv get "HUB_ELABORATE" | sed "s/,/ /g")"
FILES="$FILES $($dotenv get "HUB_KUECONFIG")"
FILES="$FILES $($dotenv get "HUB_BUBBLE_DNS")"
FILES="$FILES $DOT_ENV"
for f in $FILES; do
  test -f "$f" || continue
  echo "* Removing $f"
  rm -f "$f"
done

if test -L ".env"; then
  echo "* Unlinking: .env"
  unlink "$HUB_WORKDIR/.env"
fi

cat <<EOF

State has been removed.

This operation does not undeploy associated to the stack resources

EOF
