#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

usage()
{
cat << EOF
Used "hub api" to set kubeconfig of the stack

Usage: $(basename $0) -s STACK_DOMAIN

Parameters:
    -s --stack                  domain name of the stack
    -k --switch-kubecontext    Switch current Kubeconfig context to new context
    -o --to-std-out             Output to stdout
    -h --help                   print current messag
EOF
}

if test -z "$1"; then
    usage;
    exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
         -s | --stack )
            shift
            STACK=$1
            ;;
         -h | --help )
            usage
            exit
            ;;
         -k | --switch-kubecontext )
            SWITCH_CONTEXT=1
            ;;
         -o | --to-std-out )
            STDOUT=1
            ;;
         -  )
            STACK=$(cat /dev/stdin | xargs | cut -d " " -f1)
            ;;
        * )
            usage
            exit 1
    esac
    shift
done

export JQ_ARGS=-cMr

_KUBECONFIG=${KUBECONFIG:-$HOME/.kubeconfig}

set +e
TEMP=$(mktemp)
HUB_ARGS="$HUB_ARGS --force --output $TEMP"
hub api instance kubeconfig $HUB_ARGS $STACK > /dev/null 2>&1

if test -z "$STDOUT"; then
    echo "Saving to $_KUBECONFIG"
    KUBECONFIG="$TEMP:$_KUBECONFIG"
    kubectl config view --flatten > $_KUBECONFIG
    DOMAIN="$(params value dns.domain)"
    test -z "$SWITCH_CONTEXT" \
    || kubectl config --kubeconfig=$_KUBECONFIG use-context $DOMAIN
else
    cat $TEMP
fi

rm -f $TEMP
set -e
