#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


usage()
{
    echo "Show stack secret"
    echo "usage:"
    echo "hubctl show secret [-s domain-name] [-r secret-reference]"
    echo
    echo "Example:"
    echo "export STACK=abc.superhub.io; hubctl show -q '.parameters.component.docker.auth.basic.password' | hubctl show secret"
    exit 0
}

if ! test -t 0; then
    REF=$(cat /dev/stdin | xargs | cut -d " " -f1 | tr -d '"')
fi

while [ "$1" != "" ]; do
    case $1 in
        -s | --stack )      shift
                            HUB_DOMAIN_NAME=$1
                            ;;
        -r | --secret-ref ) shift
                            REF=$(echo $1 | tr -d '"')
                            ;;
        -h | --help )       usage
                            exit
                            ;;
        * )                 usage
                            exit 1
    esac
    shift
done

if test -z "$HUB_DOMAIN_NAME"; then
    echo "$REF"
elif test -n "$HUB_TOKEN"; then
    # shellcheck disable=SC2086
    hubctl api instance secret get $HUB_DOMAIN_NAME $REF
else
    echo "$REF"
fi
