#!/bin/sh -xe
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


HUB=${HUB:-hub}

$HUB api instance get -j "$@" |
    node $(dirname $0)/hub-api-instance-summarize-components.js
