#!/bin/bash -e
# shellcheck disable=SC2068

usage() {
  cat << EOF

Usage: $(basename "$0") <sub command>

EKS cluster node group IAM policies

Sub commands:
    attach   Attach IAM policy
    detach   Remove IAM policy
    ls       List IAM policies

EOF
}

if test -z "$@"; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
  case $1 in
    attach )      hub-eks-policy-attach $@      
                  ;;                 
    detach )      hub-eks-policy-attach $@      
                  ;;                 
    ls     )      hub-eks-policy-ls $@      
                  ;;                 
    -h | --help ) usage
                  exit
                  ;;
    * )           usage
                  exit 1
  esac
  shift
done

