#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


usage() {
  cat << EOF
Usage: hub stack backup <sub command>

Parameters:
    create          Create backup for entire stack or individual components
    show            Show the content of backup bundle
    ls              List of available backups
    elaborate       Merge bundle with the stack deployment
    tag             Add tag to backup
    untag           Drop tag from backup
EOF
}

usage
exit 1
