#!/bin/sh -e
# Copyright (c) 2022 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


if ! ./check-tools; then
    set +x
    echo "... then run 'hubctl extensions update' again"
    exit 1
fi

if which npm >/dev/null 2>&1; then
    npm ci --omit=dev --ignore-scripts --audit=false --fund=false
else
    ./bin/color w "'hubctl pull' is not available until you install Node.js and NPM"
fi
