#!/bin/sh -xe

if ! ./check-tools; then
    set +x
    echo "... then run 'hub extensions update' again"
    exit 1
fi
which npm && npm ci --omit=dev --ignore-scripts || echo "'hub pull' is not available until you install Node.js and NPM"

# Install Hub state extension
HUB_STATE_VERSION=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/agilestacks/hub-state/releases/latest" | jq -crM '.tag_name')
if ! ./hub-state -v > /dev/null 2>&1 || test "$(cat ./hub-state.version)" != "$HUB_STATE_VERSION"; then
    TEMP_DIR=$(mktemp -d || exit 2)
    mkdir -p "$TEMP_DIR"
    trap 'rm -rf $TEMP_DIR' EXIT
    curl -sLJ "https://github.com/agilestacks/hub-state/releases/download/$HUB_STATE_VERSION/hub-state_$(uname -s)_$(uname -m).tar.gz" | tar xz -C "$TEMP_DIR"
    mv "$TEMP_DIR/hub-state" .
    echo "$HUB_STATE_VERSION" > hub-state.version
fi
