#!/bin/bash -e
# shellcheck disable=SC2086
# Creates a hosted zone by domain name and returns delegation set NS records

NS_OUTPUT=text
while [ "$1" != "" ]; do
    case $1 in
        --domain-name )   shift
                          HUB_DOMAIN_NAME="$1"
                          ;;
        --json )          NS_OUTPUT="json"
                          ;;
        --verbose )       set -x
                          ;;
    esac
    shift
done

if test -z "$HUB_DOMAIN_NAME"; then
  usage
  exit 1
fi

hosted_zone_id() {
  aws $AWS_OPTS route53 list-hosted-zones \
    --output=text \
    --query 'HostedZones[?Name==`'$1'.`].Id' \
    | xargs | cut -d " " -f1 | cut -d'/' -f3
}

hosted_zone_ns() {
  aws $AWS_OPTS \
    route53 \
    get-hosted-zone \
    --id="$ZONE_ID" \
    --output="${NS_OUTPUT:-text}" \
    --query 'DelegationSet.NameServers'
}

ZONE_ID=$(hosted_zone_id "$HUB_DOMAIN_NAME") 
if test -n "$ZONE_ID"; then
  hosted_zone_ns "$ZONE_ID"
elif test -z "$ZONE_ID" && test $NS_OUTPUT = "json"; then
  echo '[]'
fi
