#!/bin/bash -e
# shellcheck disable=SC2086

set -o pipefail

usage() {
  cat << EOF
Inserts NS records into hosted zone

Usage: $(basename "$0")

Parameters:
    --zone-id             Domain name of the hosted zone
    --record-name         Name of DNS record to create
    --record-type         Default to NS
    --record-value        Value for DNS record
    --record-ttl          Default 1800
    --aws-region          AWS Region
    --aws-profile         AWS Profile
EOF
}

REC_TYPE="NS"
REC_TTL="1800"
REC_VALUE=
while [ "$1" != "" ]; do
    case $1 in
        --aws-region )    shift
                          export AWS_REGION="$1"
                          ;;
        --aws-profile )   shift
                          export AWS_PROFILE="$1"
                          ;;
        --zone-id )       shift
                          ZONE_ID="$1"
                          ;;
        --record-name )   shift
                          REC_NAME="$1"
                          ;;
        --record-type )   shift
                          REC_TYPE="$1"
                          ;;
        --record-value )  shift
                          REC_VALUE="$1"
                          ;;
        --record-ttl )    shift
                          REC_TTL="$1"
                          ;;
        -h | --help )     usage
                          exit
                          ;;
    esac
    shift
done

if  test -z "$ZONE_ID" -o -z "$REC_NAME" -o -z "$REC_VALUE"; then
  usage
  exit 1
fi

temp="$(mktemp)"
trap "rm -f $temp" EXIT
cat <<EOF > $temp
{
  "Changes": [{
    "Action": "UPSERT",
    "ResourceRecordSet": {
      "Name": "$REC_NAME",
      "Type": "$REC_TYPE",
      "TTL": $REC_TTL,
      "ResourceRecords": $REC_VALUE
  }}]
}
EOF

CHANGE=$( \
  aws $AWS_OPTS route53 change-resource-record-sets \
    --hosted-zone-id "$ZONE_ID" \
    --change-batch "file://$temp" \
    --output json \
  | jq  -Mr '.ChangeInfo.Id' )
sleep 3
aws --output text $AWS_OPTS route53 wait resource-record-sets-changed --id "$CHANGE"
