#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# shellcheck disable=SC2086

while [ "$1" != "" ]; do
    case $1 in
        --domain-name )   shift
                          HUB_DOMAIN_NAME="$1"
                          ;;
        --aws-profile )   shift
                          export AWS_PROFILE="$1"
                          ;;
        --verbose )       set -x
                          ;;
    esac
    shift
done

if test -z "$HUB_DOMAIN_NAME"; then
  echo "Error: --domain-name DOMAIN is not defined"
  exit 1
fi

aws $AWS_OPTS route53 list-hosted-zones \
    --output=text \
    --query 'HostedZones[?Name==`'$HUB_DOMAIN_NAME'.`].Id' \
    | xargs | cut -d " " -f1 | cut -d'/' -f3
