#!/bin/sh
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.

HUB_ARGS=
VERBOSE=
while test "$1" != ""; do
  case $1 in
    -V | --verbose )
      VERBOSE="true"
    ;;
    * )
      HUB_ARGS="$HUB_ARGS $1"
    ;;
  esac
  shift
done

if test "$VERBOSE" = "true"; then
  set -x
  VERBOSE="--verbose"
fi

maybe_verb=$(basename "$0" | cut -d- -f3)
if test -z "$maybe_verb"; then
  color e "Unable to find local executor"
  exit 1
fi
verb="$maybe_verb"

run_toolbox_script="$HUB_WORKDIR/.hub/.hub-toolbox"
cat << EOF > "$run_toolbox_script"
#!/bin/sh -e

export PATH="\$HUB_WORKDIR:\$HUB_WORKDIR/bin:/usr/local/share/hub/bin:\$PATH"

if test -e "\$HUB_WORKDIR/.env"; then
    eval "\$(dotenv -f "\$HUB_WORKDIR/.env" "export")"
fi;

exec hubctl $verb $HUB_ARGS
EOF
chmod +x "$run_toolbox_script"

exec hubctl toolbox $VERBOSE "$run_toolbox_script"
