#!/bin/sh
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.

HUB_ARGS=
VERBOSE=
while test "$1" != ""; do
  case $1 in
    -V | --verbose )
      VERBOSE="true"
    ;;
    * )
      HUB_ARGS="$HUB_ARGS $1"
    ;;
  esac
  shift
done

if test "$VERBOSE" = "true"; then
  set -x
  VERBOSE="--verbose"
fi

hubctl="$(which hubctl 2>/dev/null || true)"
if test -z "$hubctl"; then
  # backward compatibility
  hubctl="$(which hub 2>/dev/null || true)"
fi
if test -z "$hubctl"; then
  color error "hubctl not found in PATH. Please install hubctl first."
  exit 1
fi

maybe_verb=$(basename "$0" | cut -d- -f3)
if test -z "$maybe_verb"; then
  color e "Unable to find local executor"
  exit 1
fi
verb="$maybe_verb"

run_toolbox_script="$HUB_WORKDIR/.hub/.hub-toolbox"
cat << EOF > "$run_toolbox_script"
#!/bin/sh -e

hubctl="\$(which hubctl 2>/dev/null || true)"
if test -z "\$hubctl"; then
  hubctl="\$(which hub 2>/dev/null || true)"
fi

if test -e "\$HUB_WORKDIR/.env"; then
    set -a
    source .env
    set +a
fi;

export PATH="\$HUB_WORKDIR:\$HUB_WORKDIR/bin:/usr/local/share/hub/bin:\$PATH"

exec \$hubctl $verb $HUB_ARGS
EOF
chmod +x "$run_toolbox_script"

exec $hubctl toolbox $VERBOSE /bin/sh "$run_toolbox_script"
