#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# Simple wrapper script around hub deploy

HUB=$(which hub)
if test -z "$HUB"; then
  echo "Error: hub cli cannot be found"
  exit 1
fi

check-tools --omit-optional

# shellcheck disable=SC2068
$HUB deploy $@
