#!/bin/sh
# Copyright (c) 2022 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

hubctl="$(which hubctl 2>/dev/null || true)"
if test -z "$hubctl"; then
  # backward compatibility
  hubctl="$(which hub 2>/dev/null || true)"
fi
if test -z "$hubctl"; then
  color error "hubctl not found in PATH. Please install hubctl first."
  exit 1
fi

maybe_verb=$(basename "$0" | cut -d- -f3)
if test -z "$maybe_verb"; then
  usage
  exit 1
fi
verb="$maybe_verb"

cat << EOF >.hub-toolbox
#!/bin/bash -e

hubctl="\$(which hubctl 2>/dev/null || true)"
if test -z "\$hubctl"; then
  hubctl="\$(which hub 2>/dev/null || true)"
fi

if test -e .env; then
    set -a;
    source .env;
fi;

PATH="\$HUB_WORKDIR:\$HUB_WORKDIR/bin:/usr/local/share/hub/bin:\$PATH"

exec \$hubctl $verb $*
EOF

exec $hubctl toolbox bash .hub-toolbox
