#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


r53_undeploy="$(files -e find-in-path aws/route53/undeploy)"
r53_zoneid="$(files -e find-in-path aws/route53/zone-id)"

echo "Starting AWS cleanup... $HUB_DOMAIN_NAME"

if test -n "$HUB_DOMAIN_NAME"; then
  zone_id=$($r53_zoneid --domain-name "$HUB_DOMAIN_NAME")
  if test -n "$zone_id"; then
    $r53_undeploy --domain-name "$HUB_DOMAIN_NAME"
  fi
fi

if test -n "$HUB_STATE_BUCKET"; then
  color w << EOF
* Bucket s3://$HUB_STATE_BUCKET is not deleted automatically.
  It contains deployments state objects.
  Please, delete it manually if you don't need it anymore.
EOF
fi
