#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.

NS_OUTPUT=text
while [ "$1" != "" ]; do
    case $1 in
        --domain-name )  shift
                         HUB_DOMAIN_NAME="$1"
                         ;;
        --json )         NS_OUTPUT=json
                         ;;
        --verbose )      set -x
                         ;;
    esac
    shift
done

if test -z "$HUB_DOMAIN_NAME"; then
  echo "Flag --domain-name VALUE not defined"
  exit 1
fi

if test "$NS_OUTPUT" = "json"; then
  JQ_OPTS=".nameServers"
else
  JQ_OPTS="-r .nameServers[]"
fi

# shellcheck disable=SC2086
if az network dns zone show $AZ_OPTS -n "$HUB_DOMAIN_NAME" -o json | jq $JQ_OPTS; then
  exit
fi
if test "$NS_OUTPUT" = n"json"; then
  echo '[]'
fi
