#!/bin/bash -e
# shellcheck disable=SC2068,SC2086,SC2155

usage() {
  echo "Check Kubernetes cluster is reachable"
}

checkCluster() {
  local KUBECONTEXT
  if test -n "$1";then
    KUBECONFIG="$1"
    export KUBECONFIG
    echo "* Trying kubeconfig: $KUBECONFIG"
  fi
  KUBECONTEXT="$2"

  if test -z "$KUBECONTEXT"; then
    KUBECONTEXT="$(kubectl config current-context)"
  fi

  if test -z "$(kubectl config view -o json | jq ".contexts[] | select(.name==\"$KUBECONTEXT\").name")"; then
    echo "* Context $KUBECONTEXT: not found"
    return 1
  fi
  echo "* Context $KUBECONTEXT: exist"

  echo -n "* Checking connectivty to $KUBECONTEXT: "
  if kubectl cluster-info --context="$KUBECONTEXT"> /dev/null; then
    echo "connected"
  else
    return $?
  fi
}

checkClusterAndSave() {
  if checkCluster "$1" "$HUB_DOMAIN_NAME"; then
    mkdir -p "$(dirname "$SAVETO")"
    "$(dirname "$0")/configure-kubeconfig" \
      --kubeconfig "$1" \
      --kubecontext "$HUB_DOMAIN_NAME" \
      --domain-name "$HUB_DOMAIN_NAME" \
      --save-to "$SAVETO"
    echo "* Saving HUB_KUBECONFIG configuration: $SAVETO"
    $dotenv set "HUB_KUBECONFIG=\"$SAVETO\""
  else
    return $?
  fi
}

dotenv="$(dirname "$(dirname "$0")")/env/dotenv -f .env"
if test -f ".env"; then
  set +a
  eval "$($dotenv "export")"
  set -a
fi

echo "Finalizing kubernetes deployment"

HUB_KUBECONFIG=$($dotenv get "HUB_KUBECONFIG")
HUB_DOMAIN_NAME=$($dotenv get "HUB_DOMAIN_NAME")
if test -n "$HUB_KUBECONFIG"; then
  echo "* File .env already provides HUB_KUBECONFIG: $HUB_KUBECONFIG"
  if checkCluster "$HUB_KUBECONFIG" "$HUB_DOMAIN_NAME"; then
    exit 0
  fi
else
  echo "* File .env does not provide HUB_KUBECONFIG"
fi

SAVETO="$(pwd)/.hub/env/$HUB_DOMAIN_NAME.kubeconfig"
if test -f "$SAVETO"; then
  if checkClusterAndSave "$SAVETO"; then
    exit 0
  fi
else
  echo "* Kubeconfig $SAVETO: not found"
fi

if test -z "$HUB_STATE"; then
  HUB_STATE=".hub/$HUB_DOMAIN_NAME.state"
fi

cat << EOF
* Trying kubeconfig from state: $STATEFILE
* Running CLI command:

  $ hub kubeconfig -k $HUB_STATE -c $HUB_DOMAIN_NAME

EOF
{
  _kubeconfig="$KUBECONFIG"
  _temp=$(mktemp)
  export KUBECONFIG="$_temp"
  # shellcheck disable=SC2064
  trap "rm -f $_temp" EXIT
  if hub kubeconfig -k "$HUB_STATE" -c "$HUB_DOMAIN_NAME"; then
    if checkClusterAndSave "$KUBECONFIG" ; then
      exit 0
    fi
  fi
  export KUBECONFIG="$_kubeconfig"
}

if test -n "$KUBECONFIG" && checkClusterAndSave "$KUBECONFIG" ; then
  exit 0
fi

if test -f "$HOME/.kube/config"; then
  if checkClusterAndSave "$HOME/.kube/config" ; then
    exit 0
  fi
else
  echo "Kubeconfig $HOME/.kube/config: not found"
fi

if test -d "/var/run/secrets/kubernetes.io/serviceaccount"; then
  echo "Trying from: /var/run/secrets/kubernetes.io/serviceaccount"
  _temp=$(mktemp)
  # shellcheck disable=SC2064
  trap "rm -f $_temp" EXIT
  "$(dirname "$0")/configure-local-sa" --domain-name "$HUB_DOMAIN_NAME" --save-to "$_temp"
  if checkClusterAndSave "$_temp"; then
    exit 0
  fi
fi

echo "Error: unable to configure kubeconfig!"
exit 1
