#!/bin/bash -e
# Copyright (c) 2022 EPAM Systems, Inc.
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# shellcheck disable=SC2068,SC2086,SC2155

usage() {
  cat << EOF
Check if kubernetes cluster has been reachable
EOF
}

if test ! -f ".env"; then
  color err "Error: cannot find .env file. Please run 'hub configure'"
  exit 1
fi

dotenv="dotenv -f $HUB_WORKDIR/.env"
set +a
eval "$($dotenv "export")"
set -a

hub_kubeconfig=$($dotenv get "HUB_KUBECONFIG")
if test -n "$hub_kubeconfig"; then
  KUBECONFIG=$($dotenv get "HUB_KUBECONFIG" --default "$KUBECONFIG")
  export KUBECONFIG
  echo -n "* Using kubeconfig:"
  color bold "$KUBECONFIG"
else
  color warn "* Warning: expected variable HUB_KUBECONFIG has not been found in .env file"
  color warn "  This may lead to invalid deployment of the kubenretes components"
fi

echo -n "* Checking connectivity to cluster: "
if kubectl cluster-info > /dev/null; then
  color bold "Connected"
else
  exit 2
fi

if test "$(kubectl config current-context)" != "$HUB_DOMAIN_NAME"; then
  echo -n "* Setting $HUB_DOMAIN_NAME kube-context to: "
  if ! kubectl config set-context "$HUB_DOMAIN_NAME"; then
    color warn "* Warning: encountered error setting kubectontext to $HUB_DOMAIN_NAME"
  fi
fi
