#!/bin/bash -e
# Simple wrapper script around hub deploy however it will use pod (see ./template)

# shellcheck disable=SC2046
dotenv="$(dirname $(dirname $(dirname "$0")))/env/dotenv -f .env"
if test -f ".env"; then
  eval "$($dotenv export -f ".env" )"
fi

TOOLBOX_NAMESPACE=${TOOLBOX_NAMESPACE:-automation-tasks}
ID=$(uuidgen | tr '[:upper:]' '[:lower:]' | tr -d - | cut -c-8)

HUB_ARGS=$*
while (( "$#" )); do
  case $1 in
    -s | --state )
      shift
      STATE_FILE=$1
      break
    ;;
  esac
  shift
done

finalize() {
  rv=$?
  echo
  echo "Stand by while gracefully terminating toolbox-$ID"
  set +e
  # TODO: $kubectl exec "toolbox-$ID" -- tar cf - STATE_FILEs | tar xf - -C STATE_FILEs
  # Will be better but harder to implement
  for f in ${STATE_FILE//,/ }; do
    if ! echo "$f" | grep -e ':\/\/' >/dev/null 2>&1; then
      echo -n "* Downloading hub state to $(basename "$f"): "
      $kubectl cp "toolbox-$ID:$f" "$f" >/dev/null 2>&1;
      echo "Done"
    fi
  done
  set -e
  echo "* Cleaning toolbox-$ID: "
  {
    kubectl delete -f "$1" --wait --timeout=300s >/dev/null
    rm -rf "$1"
  } &
  if test "$rv" != "0"; then
    echo "Aborted!"
  fi
}

echo "Starting toolbox pod: toolbox-$ID"
temp=$(mktemp)
trap "finalize $temp" EXIT

echo "* Using kubeconfig: $hub_kubeconfig"
hub_kubeconfig=$($dotenv get HUB_KUBECONFIG --default "$KUBECONFIG")
"$(dirname "$0")/template" \
  --exec-id "$ID" \
  --kubeconfig "$hub_kubeconfig" \
  --namespace="$TOOLBOX_NAMESPACE" > "$temp"

kubectl="kubectl -n $TOOLBOX_NAMESPACE"
echo -n "* Checking presence of $TOOLBOX_NAMESPACE: "
if ! kubectl get namespace "$TOOLBOX_NAMESPACE" -o "name" 2>/dev/null; then
  echo "not found"
  echo -n "Deploying namespace: "
  kubectl create namespace "$TOOLBOX_NAMESPACE"
fi

echo -n "* Scheduling a pod toolbox-$ID: "
if $kubectl -f "$temp" apply >/dev/null; then
  echo "Done"
else
  exit $?
fi
echo -n "* Starting pod toolbox-$ID: "
$kubectl wait "pod/toolbox-$ID" \
  --for=condition=Ready \
  --timeout=1200s

# this do not archive directories thus no directory permissions are restored
echo -n "* Synchronizing working directory (may take few minutes): "
find -L "." \
  -type f \
  ! -path '*/.git/*' \
  ! -path '*/.helm/*' \
  ! -path '*/.terraform/*' \
  ! -path '*/.cache/*' \
  ! -path './.envrc' \
  ! -path './.env' \
  ! -path './.kubeconfig' \
  -print0 \
  | tar cz --null -T - \
  | $kubectl exec -i "toolbox-$ID" -- gosu "$USER" tar xz
echo "Done"

cloud=$($dotenv get HUB_CLOUD_PROVIDER)
if test -n "$cloud"; then
  echo -n "* Mounting $cloud credentials: "
  case "$cloud" in
    "aws" )
      shift
      "$(dirname "$0")/aws" \
        --namespace "$TOOLBOX_NAMESPACE" \
        --pod "toolbox-$ID" \
        --profile "$($dotenv get AWS_PROFILE)" && echo "Done"
    ;;
    * )
      echo "Warning: $cloud provider not yet supported!"
    ;;
  esac
fi

# shellcheck disable=SC2086
$kubectl exec -ti "toolbox-$ID" -- gosu "$USER" tini -s -- $hub $HUB_ARGS
