#!/bin/bash -e
# A wrapper around `hub` however it will use pod (see ./template)

set -o pipefail

usage() {
    cat << EOF

Launch Hub CLI in a Toolbox pod

Parameters:
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message
EOF
}

# shellcheck disable=SC2046
dotenv="$(dirname $(dirname $(dirname "$0")))/env/dotenv -f .env"
if test -f ".env"; then
  eval "$($dotenv export -f ".env" )"
fi

TOOLBOX_NAMESPACE=${TOOLBOX_NAMESPACE:-automation-tasks}
ID=$(uuidgen | tr '[:upper:]' '[:lower:]' | tr -d - | cut -c-8)

HUB_ARGS=
PASS_ENV=
while [ "$1" != "" ]; do
  case $1 in
    -s | --state )
      shift
      STATE_FILE=$1
      HUB_ARGS="$HUB_ARGS -s $STATE_FILE"
    ;;
    -e | --pass-env )
      shift
      PASS_ENV="--pass-env $1"
    ;;
    -V | --verbose )
      set -x
    ;;
    -h | --help )
      usage
      exit
    ;;
    * )
      HUB_ARGS="$HUB_ARGS $1"
    ;;
  esac
  shift
done

finalize() {
  rv=$?
  echo
  echo "Stand by while gracefully terminating toolbox-$ID"
  set +e
  # TODO: $kubectl exec "toolbox-$ID" -- tar cf - STATE_FILEs | tar xf - -C STATE_FILEs
  # Will be better but harder to implement
  for f in ${STATE_FILE//,/ }; do
    if ! echo "$f" | grep -F :// >/dev/null; then
      echo -n "* Downloading hub state to $(basename "$f"): "
      $kubectl cp "toolbox-$ID:$f" "$f" >/dev/null 2>&1
      echo "Done"
    fi
  done
  set -e
  echo "* Cleaning toolbox-$ID: "
  {
    kubectl delete -f "$1" --wait --timeout=300s >/dev/null
    rm -rf "$1"
  } &
  if test "$rv" != "0"; then
    echo "Aborted!"
  fi
}

echo "Starting toolbox pod: toolbox-$ID"
temp=$(mktemp)
# shellcheck disable=SC2064
trap "finalize $temp" EXIT

echo "* Using kubeconfig: $hub_kubeconfig"
hub_kubeconfig=$($dotenv get HUB_KUBECONFIG --default "$KUBECONFIG")
# shellcheck disable=SC2086
"$(dirname "$0")/template" \
  $PASS_ENV \
  --exec-id "$ID" \
  --kubeconfig "$hub_kubeconfig" \
  --namespace "$TOOLBOX_NAMESPACE" > "$temp"

kubectl="kubectl -n $TOOLBOX_NAMESPACE"
echo -n "* Checking presence of $TOOLBOX_NAMESPACE: "
if ! kubectl get namespace "$TOOLBOX_NAMESPACE" -o "name" 2>/dev/null; then
  echo "not found"
  echo -n "Deploying namespace: "
  kubectl create namespace "$TOOLBOX_NAMESPACE"
fi

echo -n "* Scheduling a pod toolbox-$ID: "
if $kubectl -f "$temp" apply >/dev/null; then
  rm -f "$temp"
  echo "Done"
else
  exit $?
fi
echo -n "* Starting pod toolbox-$ID: "
$kubectl wait "pod/toolbox-$ID" \
  --for=condition=Ready \
  --timeout=1200s

if test -n "$TOOLBOX_APK_ADD"; then
  echo "* Adding APK $TOOLBOX_APK_ADD:"
  $kubectl exec -i "toolbox-$ID" -- sh -c "apk update && apk add --no-cache $TOOLBOX_APK_ADD"
fi

# this do not archive directories thus no directory permissions are restored
echo -n "* Synchronizing working directory (may take few minutes): "
find -L "." \
  -type f \
  ! -path '*/.git/*' \
  ! -path '*/.helm/*' \
  ! -path '*/.terraform/*' \
  ! -path '*/.cache/*' \
  ! -path './.envrc' \
  ! -path './.env' \
  ! -path './.kubeconfig' \
  -print0 \
  | tar cz --null -T - \
  | $kubectl exec -i "toolbox-$ID" -- gosu "$USER" tar xz
echo "Done"

cloud=$($dotenv get HUB_CLOUD_PROVIDER)
if test -n "$cloud"; then
  echo -n "* Mounting $cloud credentials: "
  case "$cloud" in
    "aws" )
      "$(dirname "$0")/aws" \
        --namespace "$TOOLBOX_NAMESPACE" \
        --pod "toolbox-$ID" \
        --profile "$($dotenv get AWS_PROFILE)" && echo "Done"
    ;;
    * )
      echo "Warning: $cloud provider not yet supported!"
    ;;
  esac
fi

hub=hub
if test -n "$TOOLBOX_HUB_CLI_REPLACEMENT" -a -f "$TOOLBOX_HUB_CLI_REPLACEMENT"; then
  echo -n "* Replacing Hub CLI binary: "
  gzip -c "$TOOLBOX_HUB_CLI_REPLACEMENT" \
    | $kubectl exec -i "toolbox-$ID" -- sh -c "gzip -dc >hub; chmod +x hub"
  echo "Done"
  hub=./hub
fi

maybe_tty=
if test -t 0; then
  maybe_tty=t
fi
echo -n "* Executing: "
# shellcheck disable=SC2086
echo $kubectl exec -i$maybe_tty "toolbox-$ID" -- gosu "$USER" tini -s -- $hub $HUB_ARGS
# shellcheck disable=SC2086
exec $kubectl exec -i$maybe_tty "toolbox-$ID" -- gosu "$USER" tini -s -- $hub $HUB_ARGS
