#!/bin/bash -e

usage() {
    cat << EOF

Emit toolbox pod template

Parameters:
    --label               Use these labels for toolbox pod (can repeat multiple)
    --image               Image of toolbox (default: agilestacks/toolbox:latest)
    -e  --pass-env        Pass environment variables VAR1,VAR2,...
    -V  --verbose         Verbose outputs for debug purpose
    -h  --help            Print this message
EOF
}

IMAGE=${IMAGE:-agilestacks/toolbox}
NAMESPACE="automation-tasks"
PASS_ENV=
while [ "$1" != "" ]; do
    case $1 in
        --namespace )
          shift
          NAMESPACE=$1
        ;;
        --image )
          shift
          IMAGE=$1
        ;;
        -l | --label )
          shift
          LABELS=$(test -z "$LABELS" echo "$LABELS,$1" && echo "$1")
        ;;
        --exec-id )
          shift
          ID="$1"
        ;;
        --kubeconfig )
          shift
          KUBECONFIG="$1"
          export KUBECONFIG
        ;;
        -e | --pass-env )
          shift
          PASS_ENV=$1
        ;;
        -V | --verbose )
          set -x
        ;;
        -h | --help )
          usage
          exit
        ;;
    esac
    shift
done

# shellcheck disable=SC2046
dotenv="$(dirname $(dirname $(dirname $0)))/env/dotenv -f .env"
# shellcheck disable=SC2086,SC2046
cat <<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: toolbox-$ID
  namespace: $NAMESPACE
  labels:
    provider: agilestacks.com
    app: toolbox
    exec-id: "$ID"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toolbox-$ID
  labels:
    provider: agilestacks.com
    app: toolbox
    exec-id: "$ID"
subjects:
- kind: ServiceAccount
  name: toolbox-$ID
  namespace: $NAMESPACE
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox-$ID
  namespace: $NAMESPACE
  labels:
    provider: agilestacks.com
    app: toolbox
    exec-id: "$ID"
spec:
  serviceAccountName: toolbox-$ID
  terminationGracePeriodSeconds: 2
  containers:
  - name: toolbox
    image: $IMAGE
    workingDir: "$(pwd)"
    args: ["sleep", "infinity"]
    env:
    - {name: "USER", value: "$USER"}
    - {name: "UID", value: "$(id -u)"}
    - {name: "GID", value: "$(id -g)"}
    - {name: "HOME", value: "$HOME"}
    - {name: "TF_PLUGIN_CACHE_DIR", value: "$HOME/.terraform.d/plugin-cache"}
$(env | grep -E "^(KUBECONFIG=|GOOGLE_|AZURE_|ARM_|HUB_CRYPTO_|TF_|TERM=|LANG=|LC_)|^(${PASS_ENV//,/|})=" | sed -e 's/^/    - {name: "/' -e 's/=/", value: "/'  -e 's/$/"}/')
$($dotenv keys | grep -v ^HUB_DEPLOY_PROFILE | while read -r key ; do echo '    - {name: "'$key'", value: "'$($dotenv get $key)'"}' ; done)
    - {name: "HUB_DEPLOY_PROFILE", value: "pod"}
    volumeMounts:
    - name: work-dir
      mountPath: $(pwd)
    - name: home-dir
      mountPath: $HOME
  securityContext:
    runAsUser: 0
  volumes:
  - name: work-dir
    emptyDir: {}
  - name: home-dir
    emptyDir: {}
EOF
