#!/bin/sh -e
# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://www.mozilla.org/en-US/MPL/2.0/.

jq="jq -cMr"

while [ "$1" != "" ]; do
    case $1 in
        --domain-name )  shift
                         HUB_DOMAIN_NAME="$1"
                         ;;
        --verbose )      set -x
                         ;;
    esac
    shift
done

if test -z "$HUB_DOMAIN_NAME"; then
  echo "Flag --domain-name VALUE not defined"
  exit 1
fi

ZONE_NAME=$(gcloud dns managed-zones list --filter=dnsName:"$HUB_DOMAIN_NAME" \
  --format json | $jq '.[].name' | xargs)

if gcloud dns managed-zones describe "$ZONE_NAME" \
    --format json | $jq '.nameServers|select(.)[]'; then
  exit
fi
